extends RefCounted

# ==========================================================
# CONSUMABLE ITEMS
# ----------------------------------------------------------
# Data-only item dictionary slice generated from the original
# Control/item_handler.gd item_db source.
# Do not put behavior in this file.
# ==========================================================

static func get_items() -> Dictionary:
	return {
		"repair_kit": {
		"id": "repair_kit",
		"item_id": "repair_kit",
		"name": "Repair Kit",
		"display_name": "Repair Kit",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"prep_time": 2.0,
		"load_time": 2.0,
		"execute_time": 2.0,
		"duration": 5.0,
		"heal_amount": 25,
		"repair_amount": 25,
		"hull_restore_amount": 25,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"labels": ["consumable_group_repair", "repair_hull", "support_consumable"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"shield_patch_cell": {
		"id": "shield_patch_cell",
		"item_id": "shield_patch_cell",
		"name": "Shield Patch Cell",
		"display_name": "Shield Patch Cell",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "shield_repair",
		"consumable_group": "shield_repair",
		"prep_time": 3.0,
		"load_time": 3.0,
		"execute_time": 0.25,
		"duration": 3.0,
		"shield_repair_amount": 30,
		"repair_amount": 30,
		"requires_equipped_shield": true,
		"requires_unbroken_shield": true,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_shield"],
		"tags": [
		"shield_repair_item",
		"requires_equipped_shield",
		"requires_unbroken_shield"
		],
		"enemy_logic_tags": [
		"enemy_can_use",
		"enemy_use_when_shield_damaged",
		"enemy_do_not_use_when_shield_broken"
		],
		"labels": [
		"consumable_group_shield_repair",
		"shield_repair_while_active_only",
		"support_consumable"
		],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"recharge_kit": {
		"id": "recharge_kit",
		"item_id": "recharge_kit",
		"name": "Recharge Kit",
		"display_name": "Recharge Kit",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "recharge",
		"consumable_group": "recharge",
		"prep_time": 5.0,
		"load_time": 5.0,
		"execute_time": 0.25,
		"duration": 5.0,
		"energy_restore_amount": 100,
		"recharge_to_full": true,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["recharge_energy"],
		"labels": ["consumable_group_recharge", "energy_restore", "support_consumable"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"signal_filter_drone_mk1": {
		"id": "signal_filter_drone_mk1",
		"item_id": "signal_filter_drone_mk1",
		"name": "Signal Filter Drone Mk1",
		"display_name": "Signal Filter Drone Mk1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "drone",
		"consumable_group": "drone",
		"drone_type": "signal_filter",
		"drone_group": "defense",
		"prep_time": 2.0,
		"load_time": 2.0,
		"execute_time": 0.5,
		"duration": 8.0,
		"effect_duration": 8.0,
		"applies_effect": true,
		"effect_id": "signal_filter_drone_mk1",
		"effect_type": "protection",
		"stack_rule": "replace",
		"priority": 60,
		"affects": ["todo"],
		"values": {},
		"flags": {
		"blocked_groups": ["signal"],
		"blocked_types": ["disable"],
		"blocked_tags": ["signal"]
		},
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["deploy_signal_filter_drone"],
		"labels": ["consumable_group_drone", "signal_filter_drone", "battle_v2_signal_protection"],
		"visual_labels": ["signal_filter_drone_deployed", "signal_filter_protection_active"],
		"visual_labels_on_expire": ["signal_filter_protection_expired"],
		"atlas": "drone_sheet",
		"region": Rect2(64, 128, 64, 64)
		},

		"auto_attack_drone_test_mk1": {
		"id": "auto_attack_drone_test_mk1",
		"item_id": "auto_attack_drone_test_mk1",
		"name": "Auto Attack Drone Test Mk1",
		"display_name": "Auto Attack Drone Test Mk1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "drone",
		"consumable_group": "drone",
		"drone_type": "auto_attack",
		"drone_group": "offense",
		"prep_time": 2.0,
		"load_time": 2.0,
		"execute_time": 0.5,
		"duration": 10.0,
		"effect_duration": 10.0,
		"applies_effect": false,
		"drone_auto_attack": true,
		"drone_damage_type": "hull",
		"drone_damage_value": 1.0,
		"drone_fire_interval": 0.2,
		"drone_fire_count": 50,
		"drone_hull_current": 50.0,
		"drone_hull_max": 50.0,
		"drone_shield_active": true,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["deploy_auto_attack_drone"],
		"labels": ["consumable_group_drone", "auto_attack_drone", "battle_v2_runtime_drone"],
		"visual_labels": ["auto_attack_drone_deployed", "auto_attack_drone_runtime_active"],
		"visual_labels_on_expire": ["auto_attack_drone_expired"],
		"atlas": "drone_sheet",
		"region": Rect2(192, 128, 64, 64)
		},

		"auto_moon_pie": {
		"id": "auto_moon_pie",
		"item_id": "auto_moon_pie",
		"name": "Auto Moon Pie",
		"display_name": "Auto Moon Pie",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "drone",
		"consumable_group": "drone",
		"drone_type": "auto_attack",
		"drone_group": "defense",
		"prep_time": 2.0,
		"load_time": 2.0,
		"execute_time": 0.5,
		"duration": 12.0,
		"effect_duration": 12.0,
		"applies_effect": false,
		"drone_auto_attack": true,
		"drone_damage_type": "hull",
		"drone_damage_value": 1.0,
		"drone_fire_interval": 0.25,
		"drone_fire_count": 48,
		"drone_hull_current": 70.0,
		"drone_hull_max": 70.0,
		"drone_shield_active": true,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["deploy_auto_attack_drone"],
		"labels": ["consumable_group_drone", "auto_attack_drone", "auto_moon_pie", "battle_v2_runtime_drone", "moonpie_reward"],
		"visual_labels": ["auto_attack_drone_deployed", "auto_attack_drone_runtime_active", "auto_moon_pie_deployed"],
		"visual_labels_on_expire": ["auto_attack_drone_expired", "auto_moon_pie_expired"],
		"atlas": "drone_sheet",
		"region": Rect2(192, 128, 64, 64)
		},

		"buster_charge": {
		"id": "buster_charge",
		"item_id": "buster_charge",
		"name": "Buster Charge",
		"display_name": "Buster Charge",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "weapon",
		"consumable_group": "explosive",
		"prep_time": 1.5,
		"load_time": 1.5,
		"execute_time": 2.0,
		"duration": 1.5,
		"damage_type": "explosive",
		"damage_value": 36,
		"damage": 36,
		"explosive_damage": 36,
		"explosive_pass_percent": 0.25,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["use_buster"],
		"labels": ["consumable_group_explosive", "damage_type_explosive", "explosive_pass_damage"],
		"atlas": "item_sheet_test",
		"region": Rect2(103, 11, 34, 32)
		},

		"breach_charge": {
		"id": "breach_charge",
		"item_id": "breach_charge",
		"name": "Breach Charge",
		"display_name": "Breach Charge",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "weapon",
		"consumable_group": "explosive",
		"prep_time": 2.0,
		"load_time": 2.0,
		"execute_time": 2.5,
		"duration": 2.0,
		"damage_type": "explosive",
		"damage_value": 52,
		"damage": 52,
		"explosive_damage": 52,
		"explosive_pass_percent": 0.35,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["use_breach_charge"],
		"labels": ["consumable_group_explosive", "damage_type_explosive", "explosive_pass_damage"],
		"atlas": "item_sheet_test",
		"region": Rect2(136, 11, 34, 32)
		},

		"smart_guy_patch_cell": {
		"id": "smart_guy_patch_cell",
		"item_id": "smart_guy_patch_cell",
		"name": "Smart Guy Patch Cell",
		"display_name": "Smart Guy Patch Cell",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"prep_time": 4.0,
		"load_time": 4.0,
		"execute_time": 0.25,
		"duration": 4.0,
		"heal_amount": 20,
		"repair_amount": 20,
		"hull_restore_amount": 20,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"labels": [
		"enemy_consumable",
		"smart_guy_item",
		"consumable_group_repair",
		"repair_hull",
		"support_consumable"
		],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"fragmentation_pod": {
		"id": "fragmentation_pod",
		"item_id": "fragmentation_pod",
		"name": "Fragmentation Pod",
		"display_name": "Fragmentation Pod",
		
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "explosive",
		"consumable_group": "explosive",
		"group": "explosive",
		"slot": "consumable",
		
		"consumable": true,
		"stackable": true,
		"max_stack": 9,
		"installed_only": false,
		
		"damage_type": "explosive",
		"damage_value": 26,
		"damage": 26,
		"explosive_damage": 26,
		"explosive_pass_percent": 0.20,
		
		"prep_time": 4.0,
		"load_time": 4.0,
		"execute_time": 0.4,
		"duration": 4.0,
		
		"energy_cost": 0,
		
		"grants_actions": ["load_consumable"],
		
		"labels": [
		"consumable",
		"enemy_consumable",
		"consumable_group_explosive",
		"damage_type_explosive",
		"explosive_pass_damage"
		],
		
		"atlas": "item_sheet_test",
		"region": Rect2(80, 120, 34, 32)
		},

		"field_repair_spray_mk1": {
		"id": "field_repair_spray_mk1",
		"item_id": "field_repair_spray_mk1",
		"name": "Field Repair Spray MK1",
		"display_name": "Field Repair Spray MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "player_battle_consumable",
		"meta_score": 100,
		"meta_effect_strength": 35,
		"prep_time": 3.0,
		"load_time": 3.0,
		"execute_time": 0.25,
		"duration": 3.0,
		"heal_amount": 35,
		"repair_amount": 35,
		"hull_restore_amount": 35,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"labels": ["player_consumable", "consumable_group_repair", "repair_hull", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"emergency_capacitor_cell_mk2": {
		"id": "emergency_capacitor_cell_mk2",
		"item_id": "emergency_capacitor_cell_mk2",
		"name": "Emergency Capacitor Cell MK2",
		"display_name": "Emergency Capacitor Cell MK2",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "recharge",
		"consumable_group": "recharge",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "player_battle_consumable",
		"meta_score": 150,
		"meta_effect_strength": 65,
		"prep_time": 3.4,
		"load_time": 3.4,
		"execute_time": 0.25,
		"duration": 3.4,
		"energy_restore_amount": 65,
		"recharge_to_full": false,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["recharge_energy"],
		"labels": ["player_consumable", "consumable_group_recharge", "energy_restore", "support_consumable", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"hull_biter_charge_mk3": {
		"id": "hull_biter_charge_mk3",
		"item_id": "hull_biter_charge_mk3",
		"name": "Hull Biter Charge MK3",
		"display_name": "Hull Biter Charge MK3",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "weapon",
		"consumable_group": "explosive",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "player_battle_consumable",
		"meta_score": 200,
		"meta_effect_strength": 48,
		"prep_time": 3.6,
		"load_time": 3.6,
		"execute_time": 0.6,
		"duration": 3.6,
		"damage_type": "explosive",
		"damage_value": 48,
		"damage": 48,
		"explosive_damage": 48,
		"explosive_pass_percent": 0.32,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["use_hull_biter_charge"],
		"labels": ["player_consumable", "consumable_group_explosive", "damage_type_explosive", "explosive_pass_damage", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(103, 11, 34, 32)
		},

		"vayrax_hull_knit_cell_mk1": {
		"id": "vayrax_hull_knit_cell_mk1",
		"item_id": "vayrax_hull_knit_cell_mk1",
		"name": "Vayrax Hull Knit Cell MK1",
		"display_name": "Vayrax Hull Knit Cell MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "enemy_battle_consumable",
		"meta_score": 110,
		"meta_effect_strength": 22,
		"prep_time": 3.2,
		"load_time": 3.2,
		"execute_time": 0.25,
		"duration": 3.2,
		"heal_amount": 22,
		"repair_amount": 22,
		"hull_restore_amount": 22,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"enemy_logic_tags": ["enemy_can_use", "enemy_use_when_hull_damaged"],
		"labels": ["enemy_consumable", "vayrax_item", "consumable_group_repair", "repair_hull", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"raider_hot_patch_canister_mk2": {
		"id": "raider_hot_patch_canister_mk2",
		"item_id": "raider_hot_patch_canister_mk2",
		"name": "Raider Hot Patch Canister MK2",
		"display_name": "Raider Hot Patch Canister MK2",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "enemy_battle_consumable",
		"meta_score": 165,
		"meta_effect_strength": 34,
		"prep_time": 4.0,
		"load_time": 4.0,
		"execute_time": 0.25,
		"duration": 4.0,
		"heal_amount": 34,
		"repair_amount": 34,
		"hull_restore_amount": 34,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"enemy_logic_tags": ["enemy_can_use", "enemy_use_when_hull_damaged"],
		"labels": ["enemy_consumable", "raider_item", "consumable_group_repair", "repair_hull", "support_consumable", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"guardian_shield_fuse_cell_mk3": {
		"id": "guardian_shield_fuse_cell_mk3",
		"item_id": "guardian_shield_fuse_cell_mk3",
		"name": "Guardian Shield Fuse Cell MK3",
		"display_name": "Guardian Shield Fuse Cell MK3",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "shield_repair",
		"consumable_group": "shield_repair",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "enemy_battle_consumable",
		"meta_score": 220,
		"meta_effect_strength": 45,
		"prep_time": 3.2,
		"load_time": 3.2,
		"execute_time": 0.25,
		"duration": 3.2,
		"shield_repair_amount": 45,
		"repair_amount": 45,
		"requires_equipped_shield": true,
		"requires_unbroken_shield": true,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_shield"],
		"tags": ["shield_repair_item", "requires_equipped_shield", "requires_unbroken_shield"],
		"enemy_logic_tags": ["enemy_can_use", "enemy_use_when_shield_damaged", "enemy_do_not_use_when_shield_broken"],
		"labels": ["enemy_consumable", "guardian_item", "consumable_group_shield_repair", "shield_repair_while_active_only", "support_consumable", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"field_repair_spray_mk1_1": {
		"id": "field_repair_spray_mk1",
		"item_id": "field_repair_spray_mk1",
		"name": "Field Repair Spray MK1",
		"display_name": "Field Repair Spray MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"tier": 1,
		"prep_time": 3.0,
		"load_time": 3.0,
		"execute_time": 0.25,
		"duration": 3.0,
		"heal_amount": 18,
		"repair_amount": 18,
		"hull_restore_amount": 18,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"labels": ["player_consumable", "consumable_group_repair", "repair_hull", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"emergency_capacitor_cell_mk1": {
		"id": "emergency_capacitor_cell_mk1",
		"item_id": "emergency_capacitor_cell_mk1",
		"name": "Emergency Capacitor Cell MK1",
		"display_name": "Emergency Capacitor Cell MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "recharge",
		"consumable_group": "recharge",
		"tier": 1,
		"prep_time": 3.5,
		"load_time": 3.5,
		"execute_time": 0.25,
		"duration": 3.5,
		"energy_restore_amount": 65,
		"recharge_to_full": false,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["recharge_energy"],
		"labels": ["player_consumable", "consumable_group_recharge", "energy_restore", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"hull_biter_charge_mk1": {
		"id": "hull_biter_charge_mk1",
		"item_id": "hull_biter_charge_mk1",
		"name": "Hull Biter Charge MK1",
		"display_name": "Hull Biter Charge MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "weapon",
		"consumable_group": "explosive",
		"tier": 1,
		"prep_time": 2.4,
		"load_time": 2.4,
		"execute_time": 0.5,
		"duration": 2.4,
		"damage_type": "explosive",
		"damage_value": 34,
		"damage": 34,
		"explosive_damage": 34,
		"explosive_pass_percent": 0.30,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["use_hull_biter_charge"],
		"labels": ["player_consumable", "consumable_group_explosive", "damage_type_explosive", "explosive_pass_damage", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(103, 11, 34, 32)
		},

		"vayrax_hull_knit_cell_mk1_1": {
		"id": "vayrax_hull_knit_cell_mk1",
		"item_id": "vayrax_hull_knit_cell_mk1",
		"name": "Vayrax Hull Knit Cell MK1",
		"display_name": "Vayrax Hull Knit Cell MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"tier": 1,
		"prep_time": 3.2,
		"load_time": 3.2,
		"execute_time": 0.25,
		"duration": 3.2,
		"heal_amount": 22,
		"repair_amount": 22,
		"hull_restore_amount": 22,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"enemy_logic_tags": ["enemy_can_use", "enemy_use_when_hull_damaged"],
		"labels": ["enemy_consumable", "vayrax_item", "consumable_group_repair", "repair_hull", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"raider_hot_patch_canister_mk1": {
		"id": "raider_hot_patch_canister_mk1",
		"item_id": "raider_hot_patch_canister_mk1",
		"name": "Raider Hot Patch Canister MK1",
		"display_name": "Raider Hot Patch Canister MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"tier": 1,
		"prep_time": 4.0,
		"load_time": 4.0,
		"execute_time": 0.25,
		"duration": 4.0,
		"heal_amount": 32,
		"repair_amount": 32,
		"hull_restore_amount": 32,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"enemy_logic_tags": ["enemy_can_use", "enemy_use_when_hull_damaged"],
		"labels": ["enemy_consumable", "raider_item", "consumable_group_repair", "repair_hull", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"guardian_shield_fuse_cell_mk1": {
		"id": "guardian_shield_fuse_cell_mk1",
		"item_id": "guardian_shield_fuse_cell_mk1",
		"name": "Guardian Shield Fuse Cell MK1",
		"display_name": "Guardian Shield Fuse Cell MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "shield_repair",
		"consumable_group": "shield_repair",
		"tier": 1,
		"prep_time": 3.2,
		"load_time": 3.2,
		"execute_time": 0.25,
		"duration": 3.2,
		"shield_repair_amount": 40,
		"repair_amount": 40,
		"requires_equipped_shield": true,
		"requires_unbroken_shield": true,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_shield"],
		"tags": ["shield_repair_item", "requires_equipped_shield", "requires_unbroken_shield"],
		"enemy_logic_tags": ["enemy_can_use", "enemy_use_when_shield_damaged", "enemy_do_not_use_when_shield_broken"],
		"labels": ["enemy_consumable", "guardian_item", "consumable_group_shield_repair", "shield_repair_while_active_only", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"planetary_resource_rover": {
		"id": "planetary_resource_rover",
		"item_id": "planetary_resource_rover",
		"name": "Planetary Resource Rover",
		"display_name": "Planetary Resource Rover",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "orbit_tool",
		"consumable_group": "orbit_tool",
		"orbit_item_type": "planetary_resource_rover",
		"tier": 1,
		"prep_time": 2.5,
		"load_time": 2.5,
		"execute_time": 0.5,
		"duration": 2.5,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"consume_on_use": true,
		"consumed_on_use": true,
		"installed_only": false,
		"orbit_only": true,
		"usable_in_main_mode": false,
		"usable_in_battle": false,
		"authored_only": true,
		"planet_surface_tool": true,
		"planetary_resource_action": "explore",
		"orbit_operation_ids": ["planetary_rover_explore"],
		"grants_actions": ["planetary_rover_explore"],
		"description": "A disposable rover package deployed from orbit to explore planet resource data. Data-only pass; no landing UI.",
		"tags": ["orbit_tool", "planetary_resource_tool", "single_use", "data_only_surface_explore"],
		"labels": ["player_consumable", "orbit_tool", "planetary_resource_tool", "planetary_resource_rover", "consumed_on_use", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(103, 11, 34, 32)
		},

		"planet_recovery_launcher": {
		"id": "planet_recovery_launcher",
		"item_id": "planet_recovery_launcher",
		"name": "Planet Recovery Launcher",
		"display_name": "Planet Recovery Launcher",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "orbit_tool",
		"consumable_group": "orbit_tool",
		"orbit_item_type": "planet_recovery_launcher",
		"tier": 1,
		"prep_time": 2.5,
		"load_time": 2.5,
		"execute_time": 0.5,
		"duration": 2.5,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"consume_on_use": true,
		"consumed_on_use": true,
		"installed_only": false,
		"orbit_only": true,
		"usable_in_main_mode": false,
		"usable_in_battle": false,
		"authored_only": true,
		"planet_surface_tool": true,
		"planetary_resource_action": "recover_to_orbit",
		"orbit_operation_ids": ["planet_recovery_launch"],
		"grants_actions": ["planet_recovery_launch"],
		"description": "A disposable surface-to-orbit launcher for sending planet-held resources and items back to the ship.",
		"tags": ["orbit_tool", "planetary_resource_tool", "single_use", "surface_to_orbit_recovery"],
		"labels": ["player_consumable", "orbit_tool", "planetary_resource_tool", "planet_recovery_launcher", "consumed_on_use", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(136, 11, 34, 32)
		}
	}
