extends RefCounted

# ==========================================================
# SPACE MATERIAL / ASTEROID RESOURCE ITEMS
# ----------------------------------------------------------
# Data-only item dictionary slice generated from the original
# Control/item_handler.gd item_db source.
# Do not put behavior in this file.
# ==========================================================

static func get_items() -> Dictionary:
	return {
		"silicate_dust": {
		"id": "silicate_dust",
		"item_id": "silicate_dust",
		"name": "Silicate Dust",
		"display_name": "Silicate Dust",
		"type": "resource",
		"item_type": "resource",
		"subtype": "mineral",
		"resource_family": "common_rock",
		"rarity_rank": 1,
		"rarity_label": "Common",
		"meta_score": 10,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "mineral", "common_resource", "crafting_material"],
		"texture": preload("res://images/nickel.png")
		},

		"carbon_compounds": {
		"id": "carbon_compounds",
		"item_id": "carbon_compounds",
		"name": "Carbon Compounds",
		"display_name": "Carbon Compounds",
		"type": "resource",
		"item_type": "resource",
		"subtype": "compound",
		"resource_family": "organic_base",
		"rarity_rank": 2,
		"rarity_label": "Very Common",
		"meta_score": 20,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "compound", "crafting_material"],
		"texture": preload("res://images/nickel.png")
		},

		"water_ice": {
		"id": "water_ice",
		"item_id": "water_ice",
		"name": "Water Ice",
		"display_name": "Water Ice",
		"type": "resource",
		"item_type": "resource",
		"subtype": "ice",
		"resource_family": "volatile",
		"rarity_rank": 3,
		"rarity_label": "Common Volatile",
		"meta_score": 35,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "ice", "volatile", "crafting_material"],
		"texture": preload("res://images/nickel.png")
		},

		"magnesium_ore": {
		"id": "magnesium_ore",
		"item_id": "magnesium_ore",
		"name": "Magnesium Ore",
		"display_name": "Magnesium Ore",
		"type": "resource",
		"item_type": "resource",
		"subtype": "metal",
		"resource_family": "light_metal",
		"rarity_rank": 4,
		"rarity_label": "Uncommon",
		"meta_score": 50,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "metal", "light_metal", "crafting_material"],
		"texture": preload("res://images/nickel.png")
		},

		"titanium_ore": {
		"id": "titanium_ore",
		"item_id": "titanium_ore",
		"name": "Titanium Ore",
		"display_name": "Titanium Ore",
		"type": "resource",
		"item_type": "resource",
		"subtype": "metal",
		"resource_family": "structural_metal",
		"rarity_rank": 5,
		"rarity_label": "Uncommon Structural",
		"meta_score": 70,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "metal", "structural_metal", "crafting_material"],
		"texture": preload("res://images/nickel.png")
		},

		"rare_earth_mix": {
		"id": "rare_earth_mix",
		"item_id": "rare_earth_mix",
		"name": "Rare Earth Mix",
		"display_name": "Rare Earth Mix",
		"type": "resource",
		"item_type": "resource",
		"subtype": "rare_earth",
		"resource_family": "electronics_material",
		"rarity_rank": 6,
		"rarity_label": "Rare",
		"meta_score": 95,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "rare_earth", "electronics_material", "crafting_material"],
		"texture": preload("res://images/nickel.png")
		},

		"platinum_group_ore": {
		"id": "platinum_group_ore",
		"item_id": "platinum_group_ore",
		"name": "Platinum Group Ore",
		"display_name": "Platinum Group Ore",
		"type": "resource",
		"item_type": "resource",
		"subtype": "precious_metal",
		"resource_family": "advanced_catalyst",
		"rarity_rank": 7,
		"rarity_label": "Very Rare",
		"meta_score": 130,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "precious_metal", "advanced_catalyst", "crafting_material"],
		"texture": preload("res://images/nickel.png")
		},

		"helium_3": {
		"id": "helium_3",
		"item_id": "helium_3",
		"name": "Helium-3",
		"display_name": "Helium-3",
		"type": "resource",
		"item_type": "resource",
		"subtype": "isotope",
		"resource_family": "fusion_fuel",
		"rarity_rank": 8,
		"rarity_label": "Extremely Rare Fuel",
		"meta_score": 175,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "isotope", "fusion_fuel", "crafting_material"],
		"texture": preload("res://images/nickel.png")
		},

		"deuterium_crystals": {
		"id": "deuterium_crystals",
		"item_id": "deuterium_crystals",
		"name": "Deuterium Crystals",
		"display_name": "Deuterium Crystals",
		"type": "resource",
		"item_type": "resource",
		"subtype": "isotope_crystal",
		"resource_family": "reactor_material",
		"rarity_rank": 9,
		"rarity_label": "Ultra Rare",
		"meta_score": 230,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "isotope", "crystal", "reactor_material", "crafting_material"],
		"texture": preload("res://images/nickel.png")
		},

		"exotic_matter_filament": {
		"id": "exotic_matter_filament",
		"item_id": "exotic_matter_filament",
		"name": "Exotic Matter Filament",
		"display_name": "Exotic Matter Filament",
		"type": "resource",
		"item_type": "resource",
		"subtype": "exotic",
		"resource_family": "alien_physics_material",
		"rarity_rank": 10,
		"rarity_label": "Extremely Rare",
		"meta_score": 300,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "exotic", "alien_material", "crafting_material"],
		"texture": preload("res://images/nickel.png")
		},

		"chondrite_fragments": {
		"id": "chondrite_fragments",
		"item_id": "chondrite_fragments",
		"name": "Chondrite Fragments",
		"display_name": "Chondrite Fragments",
		"type": "resource",
		"item_type": "resource",
		"subtype": "mineral",
		"resource_family": "asteroid_rock",
		"source_type": "asteroid",
		"rarity_rank": 2,
		"rarity_label": "Common Asteroid Material",
		"meta_score": 18,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "asteroid_material", "mineral", "common_resource", "crafting_material"],
		"source_tags": ["asteroid"],
		"texture": preload("res://images/nickel.png")
		},

		"nickel_iron_shards": {
		"id": "nickel_iron_shards",
		"item_id": "nickel_iron_shards",
		"name": "Nickel-Iron Shards",
		"display_name": "Nickel-Iron Shards",
		"type": "resource",
		"item_type": "resource",
		"subtype": "metal",
		"resource_family": "asteroid_metal",
		"source_type": "asteroid",
		"rarity_rank": 3,
		"rarity_label": "Common Metallic Asteroid Material",
		"meta_score": 38,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "asteroid_material", "metal", "asteroid_metal", "crafting_material"],
		"source_tags": ["asteroid"],
		"texture": preload("res://images/nickel.png")
		},

		"olivine_crystals": {
		"id": "olivine_crystals",
		"item_id": "olivine_crystals",
		"name": "Olivine Crystals",
		"display_name": "Olivine Crystals",
		"type": "resource",
		"item_type": "resource",
		"subtype": "crystal",
		"resource_family": "asteroid_silicate_crystal",
		"source_type": "asteroid",
		"rarity_rank": 4,
		"rarity_label": "Uncommon Asteroid Crystal",
		"meta_score": 58,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "asteroid_material", "crystal", "silicate", "crafting_material"],
		"source_tags": ["asteroid"],
		"texture": preload("res://images/nickel.png")
		},

		"troilite_sulfide": {
		"id": "troilite_sulfide",
		"item_id": "troilite_sulfide",
		"name": "Troilite Sulfide",
		"display_name": "Troilite Sulfide",
		"type": "resource",
		"item_type": "resource",
		"subtype": "sulfide",
		"resource_family": "asteroid_sulfide",
		"source_type": "asteroid",
		"rarity_rank": 5,
		"rarity_label": "Uncommon Asteroid Sulfide",
		"meta_score": 82,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "asteroid_material", "sulfide", "metal_sulfide", "crafting_material"],
		"source_tags": ["asteroid"],
		"texture": preload("res://images/nickel.png")
		},

		"iridium_specks": {
		"id": "iridium_specks",
		"item_id": "iridium_specks",
		"name": "Iridium Specks",
		"display_name": "Iridium Specks",
		"type": "resource",
		"item_type": "resource",
		"subtype": "precious_metal",
		"resource_family": "asteroid_precious_metal",
		"source_type": "asteroid",
		"rarity_rank": 7,
		"rarity_label": "Rare Asteroid Metal",
		"meta_score": 145,
		"stackable": true,
		"max_stack": 99999,
		"consumable": false,
		"installed_only": false,
		"grants_actions": [],
		"labels": ["resource", "space_material", "asteroid_material", "precious_metal", "rare_resource", "crafting_material"],
		"source_tags": ["asteroid"],
		"texture": preload("res://images/nickel.png")
		},

		"corrupted_nav_fragment": {
		"item_id": "corrupted_nav_fragment",
		"display_name": "Corrupted Nav Fragment",
		"name": "Corrupted Nav Fragment",
		
		"type": "resource",
		"subtype": "navigation_fragment",
		"slot": "cargo",
		
		"stackable": true,
		"max_stack": 99,
		"consumable": false,
		"installed_only": false,
		
		"description": "A damaged navigation memory shard recovered from a lost relay. Its route data is broken, but not useless.",
		
		"labels": [
		"resource",
		"navigation",
		"quest_fragment",
		"relay_fragment"
		]
		}
	}
