extends RefCounted

# ==========================================================
# S1.4 PLAYER BATTLE ITEMS
# ----------------------------------------------------------
# Data-only item dictionary slice.
# Loaded by Control/items/item_db_builder.gd.
# Do not put behavior in this file.
# ==========================================================

static func get_items() -> Dictionary:
	return {
		# ======================================================
		# FS s1.4 CONTENT PASS - PLAYER BATTLE ITEMS
		# ------------------------------------------------------
		# Paste inside item_db before the enemy item section or blueprints.
		# Metrics are first-pass placeholders for later balance pass.
		# ======================================================

		# ------------------------------------------------------
		# PLAYER PRIMARY ENERGY WEAPONS
		# ------------------------------------------------------
		# ======================================================
		# FS s1.4 CONTENT PASS - TIERED BATTLE ITEMS
		# ------------------------------------------------------
		# Replace the previous FS s1.4 CONTENT PASS player/enemy battle item block with this.
		# Paste inside item_db before blueprints.
		#
		# Tier intent:
		# - Tier 1: demo-safe / early combat
		# - Tier 2: moderate upgrade / mid combat
		# - Tier 3: strong current-demo cap / boss or reward-grade
		#
		# Burst rule reminder:
		# - burst_count = separate stacked TODO fires
		# - each fire spends one ammo
		# - total ammo cost = burst_count when ammo_per_burst is 1
		# ======================================================

		# ------------------------------------------------------
		# PLAYER PRIMARY ENERGY WEAPONS - TIERS 1/2/3
		# ------------------------------------------------------
		"ion_threader_mk1": {
		"id": "ion_threader_mk1",
		"item_id": "ion_threader_mk1",
		"name": "Ion Threader MK1",
		"display_name": "Ion Threader MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "player_primary_energy",
		"meta_score": 100,
		"meta_pressure": 24,
		"damage_type": "energy",
		"damage_value": 24,
		"damage": 24,
		"duration": 2.4,
		"energy_cost": 30,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_ion_threader"],
		"labels": ["player_weapon", "primary_weapon_energy", "damage_type_energy", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"scatter_pulse_mk2": {
		"id": "scatter_pulse_mk2",
		"item_id": "scatter_pulse_mk2",
		"name": "Scatter Pulse MK2",
		"display_name": "Scatter Pulse MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "player_primary_energy",
		"meta_score": 150,
		"meta_pressure": 34,
		"damage_type": "energy",
		"damage_value": 34,
		"damage": 34,
		"duration": 3.0,
		"energy_cost": 44,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_scatter_pulse"],
		"labels": ["player_weapon", "primary_weapon_energy", "damage_type_energy", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 50, 34, 32)
		},

		"graviton_needler_mk3": {
		"id": "graviton_needler_mk3",
		"item_id": "graviton_needler_mk3",
		"name": "Graviton Needler MK3",
		"display_name": "Graviton Needler MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "player_primary_energy",
		"meta_score": 200,
		"meta_pressure": 46,
		"damage_type": "energy",
		"damage_value": 46,
		"damage": 46,
		"duration": 3.6,
		"energy_cost": 64,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_graviton_needler"],
		"labels": ["player_weapon", "primary_weapon_energy", "damage_type_energy", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		# ------------------------------------------------------
		# PLAYER SECONDARY KINETIC WEAPONS - TIERS 1/2/3
		# ------------------------------------------------------
		"coil_spitter_mk1": {
		"id": "coil_spitter_mk1",
		"item_id": "coil_spitter_mk1",
		"name": "Coil Spitter MK1",
		"display_name": "Coil Spitter MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "player_secondary_kinetic",
		"meta_score": 100,
		"meta_pressure": 56,
		"damage_type": "kinetic",
		"damage_value": 14,
		"damage": 14,
		"duration": 1.8,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 4,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_coil_spitter"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 85, 34, 32)
		},

		"flechette_burst_rack_mk2": {
		"id": "flechette_burst_rack_mk2",
		"item_id": "flechette_burst_rack_mk2",
		"name": "Flechette Burst Rack MK2",
		"display_name": "Flechette Burst Rack MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "player_secondary_kinetic",
		"meta_score": 150,
		"meta_pressure": 88,
		"damage_type": "kinetic",
		"damage_value": 22,
		"damage": 22,
		"duration": 2.6,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 4,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_flechette_burst"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 85, 34, 32)
		},

		"spike_driver_mk3": {
		"id": "spike_driver_mk3",
		"item_id": "spike_driver_mk3",
		"name": "Spike Driver MK3",
		"display_name": "Spike Driver MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "player_secondary_kinetic",
		"meta_score": 200,
		"meta_pressure": 102,
		"damage_type": "kinetic",
		"damage_value": 34,
		"damage": 34,
		"duration": 3.8,
		"energy_cost": 0,
		"weapon_group": "medium",
		"ammo_group": "medium",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_spike_driver"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_medium", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 85, 34, 32)
		},

		# ------------------------------------------------------
		# PLAYER SECONDARY EXPLOSIVE WEAPONS - TIERS 1/2/3
		# ------------------------------------------------------
		"snap_torpedo_rack_mk1": {
		"id": "snap_torpedo_rack_mk1",
		"item_id": "snap_torpedo_rack_mk1",
		"name": "Snap Torpedo Rack MK1",
		"display_name": "Snap Torpedo Rack MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "player_secondary_explosive",
		"meta_score": 100,
		"meta_pressure": 38,
		"damage_type": "explosive",
		"damage_value": 32,
		"damage": 32,
		"explosive_pass_percent": 0.18,
		"duration": 4.2,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["launch_snap_torpedo"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 120, 34, 32)
		},

		"plasma_mine_launcher_mk2": {
		"id": "plasma_mine_launcher_mk2",
		"item_id": "plasma_mine_launcher_mk2",
		"name": "Plasma Mine Launcher MK2",
		"display_name": "Plasma Mine Launcher MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "player_secondary_explosive",
		"meta_score": 150,
		"meta_pressure": 55,
		"damage_type": "explosive",
		"damage_value": 44,
		"damage": 44,
		"explosive_pass_percent": 0.26,
		"duration": 5.0,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["launch_plasma_mine"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 120, 34, 32)
		},

		"cracked_void_mortar_mk3": {
		"id": "cracked_void_mortar_mk3",
		"item_id": "cracked_void_mortar_mk3",
		"name": "Cracked Void Mortar MK3",
		"display_name": "Cracked Void Mortar MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "player_secondary_explosive",
		"meta_score": 200,
		"meta_pressure": 75,
		"damage_type": "explosive",
		"damage_value": 56,
		"damage": 56,
		"explosive_pass_percent": 0.34,
		"duration": 5.8,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_cracked_void_mortar"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 120, 34, 32)
		},

		# ------------------------------------------------------
		# PLAYER SHIELDS - TIERS 1/2/3
		# ------------------------------------------------------
		"screen_door_shield_mk1": {
		"id": "screen_door_shield_mk1",
		"item_id": "screen_door_shield_mk1",
		"name": "Screen Door Shield MK1",
		"display_name": "Screen Door Shield MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "player_shield",
		"meta_score": 100,
		"meta_capacity": 35,
		"shield_hp_max": 35,
		"base_damage_resist": 0.14,
		"base_shield_resist": 0.14,
		"regen_per_second": 3.0,
		"regen_delay": 1.5,
		"swap_time": 1.1,
		"duration": 1.1,
		"steady_energy_drain": 14.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(115, 120, 34, 32)
		},

		"pulse_guard_mk2": {
		"id": "pulse_guard_mk2",
		"item_id": "pulse_guard_mk2",
		"name": "Pulse Guard MK2",
		"display_name": "Pulse Guard MK2",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "player_shield",
		"meta_score": 150,
		"meta_capacity": 60,
		"shield_hp_max": 60,
		"base_damage_resist": 0.22,
		"base_shield_resist": 0.22,
		"regen_per_second": 2.4,
		"regen_delay": 2.0,
		"swap_time": 1.4,
		"duration": 1.4,
		"steady_energy_drain": 18.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"anchor_barrier_mk3": {
		"id": "anchor_barrier_mk3",
		"item_id": "anchor_barrier_mk3",
		"name": "Anchor Barrier MK3",
		"display_name": "Anchor Barrier MK3",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "player_shield",
		"meta_score": 200,
		"meta_capacity": 90,
		"shield_hp_max": 90,
		"base_damage_resist": 0.30,
		"base_shield_resist": 0.30,
		"regen_per_second": 1.8,
		"regen_delay": 2.4,
		"swap_time": 2.0,
		"duration": 2.0,
		"steady_energy_drain": 24.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		# ------------------------------------------------------
		# PLAYER BATTLE CONSUMABLES - TIERS 1/2/3
		# ------------------------------------------------------
		"field_repair_spray_mk1": {
		"id": "field_repair_spray_mk1",
		"item_id": "field_repair_spray_mk1",
		"name": "Field Repair Spray MK1",
		"display_name": "Field Repair Spray MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "player_battle_consumable",
		"meta_score": 100,
		"meta_effect_strength": 35,
		"prep_time": 3.0,
		"load_time": 3.0,
		"execute_time": 0.25,
		"duration": 3.0,
		"heal_amount": 35,
		"repair_amount": 35,
		"hull_restore_amount": 35,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"labels": ["player_consumable", "consumable_group_repair", "repair_hull", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"emergency_capacitor_cell_mk2": {
		"id": "emergency_capacitor_cell_mk2",
		"item_id": "emergency_capacitor_cell_mk2",
		"name": "Emergency Capacitor Cell MK2",
		"display_name": "Emergency Capacitor Cell MK2",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "recharge",
		"consumable_group": "recharge",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "player_battle_consumable",
		"meta_score": 150,
		"meta_effect_strength": 65,
		"prep_time": 3.4,
		"load_time": 3.4,
		"execute_time": 0.25,
		"duration": 3.4,
		"energy_restore_amount": 65,
		"recharge_to_full": false,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["recharge_energy"],
		"labels": ["player_consumable", "consumable_group_recharge", "energy_restore", "support_consumable", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"hull_biter_charge_mk3": {
		"id": "hull_biter_charge_mk3",
		"item_id": "hull_biter_charge_mk3",
		"name": "Hull Biter Charge MK3",
		"display_name": "Hull Biter Charge MK3",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "weapon",
		"consumable_group": "explosive",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "player_battle_consumable",
		"meta_score": 200,
		"meta_effect_strength": 48,
		"prep_time": 3.6,
		"load_time": 3.6,
		"execute_time": 0.6,
		"duration": 3.6,
		"damage_type": "explosive",
		"damage_value": 48,
		"damage": 48,
		"explosive_damage": 48,
		"explosive_pass_percent": 0.32,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["use_hull_biter_charge"],
		"labels": ["player_consumable", "consumable_group_explosive", "damage_type_explosive", "explosive_pass_damage", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(103, 11, 34, 32)
		},

		# ------------------------------------------------------
	}
