extends RefCounted

# ==========================================================
# S1.4 ENEMY BATTLE ITEMS
# ----------------------------------------------------------
# Data-only item dictionary slice.
# Loaded by Control/items/item_db_builder.gd.
# Do not put behavior in this file.
# ==========================================================

static func get_items() -> Dictionary:
	return {
		# ENEMY PRIMARY ENERGY WEAPONS - TIERS 1/2/3
		# ------------------------------------------------------
		"vayrax_needler_lance_mk1": {
		"id": "vayrax_needler_lance_mk1",
		"item_id": "vayrax_needler_lance_mk1",
		"name": "Vayrax Needler Lance MK1",
		"display_name": "Vayrax Needler Lance MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "enemy_primary_energy",
		"meta_score": 110,
		"meta_pressure": 18,
		"damage_type": "energy",
		"damage_value": 18,
		"damage": 18,
		"duration": 2.7,
		"energy_cost": 18,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_vayrax_needler_lance"],
		"labels": ["enemy_weapon", "vayrax_item", "primary_weapon_energy", "damage_type_energy", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"raider_arc_stinger_mk2": {
		"id": "raider_arc_stinger_mk2",
		"item_id": "raider_arc_stinger_mk2",
		"name": "Raider Arc Stinger MK2",
		"display_name": "Raider Arc Stinger MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "enemy_primary_energy",
		"meta_score": 165,
		"meta_pressure": 27,
		"damage_type": "energy",
		"damage_value": 27,
		"damage": 27,
		"duration": 3.0,
		"energy_cost": 23,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_raider_arc_stinger"],
		"labels": ["enemy_weapon", "raider_item", "primary_weapon_energy", "damage_type_energy", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 50, 34, 32)
		},

		"guardian_suppression_beam_mk3": {
		"id": "guardian_suppression_beam_mk3",
		"item_id": "guardian_suppression_beam_mk3",
		"name": "Guardian Suppression Beam MK3",
		"display_name": "Guardian Suppression Beam MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "enemy_primary_energy",
		"meta_score": 220,
		"meta_pressure": 36,
		"damage_type": "energy",
		"damage_value": 36,
		"damage": 36,
		"duration": 3.4,
		"energy_cost": 31,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_guardian_suppression_beam"],
		"labels": ["enemy_weapon", "guardian_item", "primary_weapon_energy", "damage_type_energy", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		# ------------------------------------------------------
		# ENEMY SECONDARY KINETIC WEAPONS - TIERS 1/2/3
		# ------------------------------------------------------
		"vayrax_splitter_rail_mk1": {
		"id": "vayrax_splitter_rail_mk1",
		"item_id": "vayrax_splitter_rail_mk1",
		"name": "Vayrax Splitter Rail MK1",
		"display_name": "Vayrax Splitter Rail MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "enemy_secondary_kinetic",
		"meta_score": 110,
		"meta_pressure": 48,
		"damage_type": "kinetic",
		"damage_value": 16,
		"damage": 16,
		"duration": 2.0,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_vayrax_splitter_rail"],
		"labels": ["enemy_weapon", "vayrax_item", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 85, 34, 32)
		},

		"raider_scrap_ripper_mk2": {
		"id": "raider_scrap_ripper_mk2",
		"item_id": "raider_scrap_ripper_mk2",
		"name": "Raider Scrap Ripper MK2",
		"display_name": "Raider Scrap Ripper MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "enemy_secondary_kinetic",
		"meta_score": 165,
		"meta_pressure": 88,
		"damage_type": "kinetic",
		"damage_value": 22,
		"damage": 22,
		"duration": 3.0,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 4,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_raider_scrap_ripper"],
		"labels": ["enemy_weapon", "raider_item", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 85, 34, 32)
		},

		"guardian_punch_driver_mk3": {
		"id": "guardian_punch_driver_mk3",
		"item_id": "guardian_punch_driver_mk3",
		"name": "Guardian Punch Driver MK3",
		"display_name": "Guardian Punch Driver MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "enemy_secondary_kinetic",
		"meta_score": 220,
		"meta_pressure": 102,
		"damage_type": "kinetic",
		"damage_value": 34,
		"damage": 34,
		"duration": 4.1,
		"energy_cost": 0,
		"weapon_group": "medium",
		"ammo_group": "medium",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_guardian_punch_driver"],
		"labels": ["enemy_weapon", "guardian_item", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_medium", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 85, 34, 32)
		},

		# ------------------------------------------------------
		# ENEMY SECONDARY EXPLOSIVE WEAPONS - TIERS 1/2/3
		# ------------------------------------------------------
		"vayrax_puncture_charge_mk1": {
		"id": "vayrax_puncture_charge_mk1",
		"item_id": "vayrax_puncture_charge_mk1",
		"name": "Vayrax Puncture Charge MK1",
		"display_name": "Vayrax Puncture Charge MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "enemy_secondary_explosive",
		"meta_score": 110,
		"meta_pressure": 44,
		"damage_type": "explosive",
		"damage_value": 36,
		"damage": 36,
		"explosive_pass_percent": 0.22,
		"duration": 4.6,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_vayrax_puncture_charge"],
		"labels": ["enemy_weapon", "vayrax_item", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 120, 34, 32)
		},

		"raider_spike_mortar_mk2": {
		"id": "raider_spike_mortar_mk2",
		"item_id": "raider_spike_mortar_mk2",
		"name": "Raider Spike Mortar MK2",
		"display_name": "Raider Spike Mortar MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "enemy_secondary_explosive",
		"meta_score": 165,
		"meta_pressure": 62,
		"damage_type": "explosive",
		"damage_value": 48,
		"damage": 48,
		"explosive_pass_percent": 0.30,
		"duration": 5.4,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_raider_spike_mortar"],
		"labels": ["enemy_weapon", "raider_item", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 120, 34, 32)
		},

		"guardian_echo_torpedo_mk3": {
		"id": "guardian_echo_torpedo_mk3",
		"item_id": "guardian_echo_torpedo_mk3",
		"name": "Guardian Echo Torpedo MK3",
		"display_name": "Guardian Echo Torpedo MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "enemy_secondary_explosive",
		"meta_score": 220,
		"meta_pressure": 82,
		"damage_type": "explosive",
		"damage_value": 60,
		"damage": 60,
		"explosive_pass_percent": 0.36,
		"duration": 6.0,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_guardian_echo_torpedo"],
		"labels": ["enemy_weapon", "guardian_item", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 120, 34, 32)
		},

		# ------------------------------------------------------
		# ENEMY SHIELDS - TIERS 1/2/3
		# ------------------------------------------------------
		"vayrax_flicker_screen_mk1": {
		"id": "vayrax_flicker_screen_mk1",
		"item_id": "vayrax_flicker_screen_mk1",
		"name": "Vayrax Flicker Screen MK1",
		"display_name": "Vayrax Flicker Screen MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "enemy_shield",
		"meta_score": 110,
		"meta_capacity": 45,
		"shield_hp_max": 45,
		"base_damage_resist": 0.18,
		"base_shield_resist": 0.18,
		"regen_per_second": 3.0,
		"regen_delay": 1.6,
		"swap_time": 1.2,
		"duration": 1.2,
		"steady_energy_drain": 16.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["enemy_shield", "vayrax_item", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(115, 120, 34, 32)
		},

		"raider_plate_screen_mk2": {
		"id": "raider_plate_screen_mk2",
		"item_id": "raider_plate_screen_mk2",
		"name": "Raider Plate Screen MK2",
		"display_name": "Raider Plate Screen MK2",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "enemy_shield",
		"meta_score": 165,
		"meta_capacity": 70,
		"shield_hp_max": 70,
		"base_damage_resist": 0.25,
		"base_shield_resist": 0.25,
		"regen_per_second": 2.1,
		"regen_delay": 2.0,
		"swap_time": 1.7,
		"duration": 1.7,
		"steady_energy_drain": 20.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["enemy_shield", "raider_item", "unit_shield_equipped", "shield_slider_scaling", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"guardian_lock_barrier_mk3": {
		"id": "guardian_lock_barrier_mk3",
		"item_id": "guardian_lock_barrier_mk3",
		"name": "Guardian Lock Barrier MK3",
		"display_name": "Guardian Lock Barrier MK3",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "enemy_shield",
		"meta_score": 220,
		"meta_capacity": 100,
		"shield_hp_max": 100,
		"base_damage_resist": 0.32,
		"base_shield_resist": 0.32,
		"regen_per_second": 1.8,
		"regen_delay": 2.5,
		"swap_time": 2.1,
		"duration": 2.1,
		"steady_energy_drain": 26.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["enemy_shield", "guardian_item", "unit_shield_equipped", "shield_slider_scaling", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		# ------------------------------------------------------
		# ENEMY BATTLE CONSUMABLES - TIERS 1/2/3
		# ------------------------------------------------------
		"vayrax_hull_knit_cell_mk1": {
		"id": "vayrax_hull_knit_cell_mk1",
		"item_id": "vayrax_hull_knit_cell_mk1",
		"name": "Vayrax Hull Knit Cell MK1",
		"display_name": "Vayrax Hull Knit Cell MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "enemy_battle_consumable",
		"meta_score": 110,
		"meta_effect_strength": 22,
		"prep_time": 3.2,
		"load_time": 3.2,
		"execute_time": 0.25,
		"duration": 3.2,
		"heal_amount": 22,
		"repair_amount": 22,
		"hull_restore_amount": 22,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"enemy_logic_tags": ["enemy_can_use", "enemy_use_when_hull_damaged"],
		"labels": ["enemy_consumable", "vayrax_item", "consumable_group_repair", "repair_hull", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"raider_hot_patch_canister_mk2": {
		"id": "raider_hot_patch_canister_mk2",
		"item_id": "raider_hot_patch_canister_mk2",
		"name": "Raider Hot Patch Canister MK2",
		"display_name": "Raider Hot Patch Canister MK2",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "enemy_battle_consumable",
		"meta_score": 165,
		"meta_effect_strength": 34,
		"prep_time": 4.0,
		"load_time": 4.0,
		"execute_time": 0.25,
		"duration": 4.0,
		"heal_amount": 34,
		"repair_amount": 34,
		"hull_restore_amount": 34,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"enemy_logic_tags": ["enemy_can_use", "enemy_use_when_hull_damaged"],
		"labels": ["enemy_consumable", "raider_item", "consumable_group_repair", "repair_hull", "support_consumable", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"guardian_shield_fuse_cell_mk3": {
		"id": "guardian_shield_fuse_cell_mk3",
		"item_id": "guardian_shield_fuse_cell_mk3",
		"name": "Guardian Shield Fuse Cell MK3",
		"display_name": "Guardian Shield Fuse Cell MK3",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "shield_repair",
		"consumable_group": "shield_repair",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "enemy_battle_consumable",
		"meta_score": 220,
		"meta_effect_strength": 45,
		"prep_time": 3.2,
		"load_time": 3.2,
		"execute_time": 0.25,
		"duration": 3.2,
		"shield_repair_amount": 45,
		"repair_amount": 45,
		"requires_equipped_shield": true,
		"requires_unbroken_shield": true,
		"stackable": true,
		"max_stack": 5,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_shield"],
		"tags": ["shield_repair_item", "requires_equipped_shield", "requires_unbroken_shield"],
		"enemy_logic_tags": ["enemy_can_use", "enemy_use_when_shield_damaged", "enemy_do_not_use_when_shield_broken"],
		"labels": ["enemy_consumable", "guardian_item", "consumable_group_shield_repair", "shield_repair_while_active_only", "support_consumable", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		}
	}
