extends RefCounted

# ==========================================================
# OLDER PLAYER BATTLE ITEMS KEPT FOR COMPATIBILITY
# ----------------------------------------------------------
# Data-only item dictionary slice.
# Loaded by Control/items/item_db_builder.gd.
# Do not put behavior in this file.
# ==========================================================

static func get_items() -> Dictionary:
	return {
		# ------------------------------------------------------
		# PLAYER SECONDARY KINETIC WEAPONS
		# ------------------------------------------------------
		"coil_spitter_mk1_1": {
		"id": "coil_spitter_mk1",
		"item_id": "coil_spitter_mk1",
		"name": "Coil Spitter MK1",
		"display_name": "Coil Spitter MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "kinetic",
		"damage_value": 14,
		"damage": 14,
		"duration": 1.8,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 4,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_coil_spitter"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 85, 34, 32)
		},

		"flechette_burst_rack_mk1": {
		"id": "flechette_burst_rack_mk1",
		"item_id": "flechette_burst_rack_mk1",
		"name": "Flechette Burst Rack MK1",
		"display_name": "Flechette Burst Rack MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "kinetic",
		"damage_value": 20,
		"damage": 20,
		"duration": 2.7,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_flechette_burst"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 85, 34, 32)
		},

		"spike_driver_mk1": {
		"id": "spike_driver_mk1",
		"item_id": "spike_driver_mk1",
		"name": "Spike Driver MK1",
		"display_name": "Spike Driver MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "kinetic",
		"damage_value": 34,
		"damage": 34,
		"duration": 4.2,
		"energy_cost": 0,
		"weapon_group": "medium",
		"ammo_group": "medium",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 2,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_spike_driver"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_medium", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 85, 34, 32)
		},

		# ------------------------------------------------------
		# PLAYER SECONDARY EXPLOSIVE WEAPONS
		# ------------------------------------------------------
		"snap_torpedo_rack_mk1_1": {
		"id": "snap_torpedo_rack_mk1",
		"item_id": "snap_torpedo_rack_mk1",
		"name": "Snap Torpedo Rack MK1",
		"display_name": "Snap Torpedo Rack MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "explosive",
		"damage_value": 32,
		"damage": 32,
		"explosive_pass_percent": 0.18,
		"duration": 4.2,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["launch_snap_torpedo"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 120, 34, 32)
		},

		"plasma_mine_launcher_mk1": {
		"id": "plasma_mine_launcher_mk1",
		"item_id": "plasma_mine_launcher_mk1",
		"name": "Plasma Mine Launcher MK1",
		"display_name": "Plasma Mine Launcher MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "explosive",
		"damage_value": 44,
		"damage": 44,
		"explosive_pass_percent": 0.28,
		"duration": 5.0,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["launch_plasma_mine"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 120, 34, 32)
		},

		"cracked_void_mortar_mk1": {
		"id": "cracked_void_mortar_mk1",
		"item_id": "cracked_void_mortar_mk1",
		"name": "Cracked Void Mortar MK1",
		"display_name": "Cracked Void Mortar MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "explosive",
		"damage_value": 58,
		"damage": 58,
		"explosive_pass_percent": 0.38,
		"duration": 6.0,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_cracked_void_mortar"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 120, 34, 32)
		},

		# ------------------------------------------------------
		# PLAYER SHIELDS
		# ------------------------------------------------------
		"screen_door_shield_mk1_1": {
		"id": "screen_door_shield_mk1",
		"item_id": "screen_door_shield_mk1",
		"name": "Screen Door Shield MK1",
		"display_name": "Screen Door Shield MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"shield_hp_max": 35,
		"base_damage_resist": 0.14,
		"base_shield_resist": 0.14,
		"regen_per_second": 3.0,
		"regen_delay": 1.5,
		"swap_time": 1.1,
		"duration": 1.1,
		"steady_energy_drain": 14.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(115, 120, 34, 32)
		},

		"pulse_guard_mk1": {
		"id": "pulse_guard_mk1",
		"item_id": "pulse_guard_mk1",
		"name": "Pulse Guard MK1",
		"display_name": "Pulse Guard MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"shield_hp_max": 60,
		"base_damage_resist": 0.22,
		"base_shield_resist": 0.22,
		"regen_per_second": 2.4,
		"regen_delay": 2.0,
		"swap_time": 1.4,
		"duration": 1.4,
		"steady_energy_drain": 18.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"anchor_barrier_mk1": {
		"id": "anchor_barrier_mk1",
		"item_id": "anchor_barrier_mk1",
		"name": "Anchor Barrier MK1",
		"display_name": "Anchor Barrier MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"shield_hp_max": 95,
		"base_damage_resist": 0.32,
		"base_shield_resist": 0.32,
		"regen_per_second": 1.8,
		"regen_delay": 2.4,
		"swap_time": 2.0,
		"duration": 2.0,
		"steady_energy_drain": 24.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		# ------------------------------------------------------
		# PLAYER BATTLE CONSUMABLES
		# ------------------------------------------------------
		"field_repair_spray_mk1_1": {
		"id": "field_repair_spray_mk1",
		"item_id": "field_repair_spray_mk1",
		"name": "Field Repair Spray MK1",
		"display_name": "Field Repair Spray MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "repair",
		"consumable_group": "repair",
		"tier": 1,
		"prep_time": 3.0,
		"load_time": 3.0,
		"execute_time": 0.25,
		"duration": 3.0,
		"heal_amount": 18,
		"repair_amount": 18,
		"hull_restore_amount": 18,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["repair_ship"],
		"labels": ["player_consumable", "consumable_group_repair", "repair_hull", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"emergency_capacitor_cell_mk1": {
		"id": "emergency_capacitor_cell_mk1",
		"item_id": "emergency_capacitor_cell_mk1",
		"name": "Emergency Capacitor Cell MK1",
		"display_name": "Emergency Capacitor Cell MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "recharge",
		"consumable_group": "recharge",
		"tier": 1,
		"prep_time": 3.5,
		"load_time": 3.5,
		"execute_time": 0.25,
		"duration": 3.5,
		"energy_restore_amount": 65,
		"recharge_to_full": false,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["recharge_energy"],
		"labels": ["player_consumable", "consumable_group_recharge", "energy_restore", "support_consumable", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(70, 11, 34, 32)
		},

		"hull_biter_charge_mk1": {
		"id": "hull_biter_charge_mk1",
		"item_id": "hull_biter_charge_mk1",
		"name": "Hull Biter Charge MK1",
		"display_name": "Hull Biter Charge MK1",
		"type": "consumable",
		"item_type": "consumable",
		"subtype": "weapon",
		"consumable_group": "explosive",
		"tier": 1,
		"prep_time": 2.4,
		"load_time": 2.4,
		"execute_time": 0.5,
		"duration": 2.4,
		"damage_type": "explosive",
		"damage_value": 34,
		"damage": 34,
		"explosive_damage": 34,
		"explosive_pass_percent": 0.30,
		"stackable": true,
		"max_stack": 10,
		"consumable": true,
		"installed_only": false,
		"grants_actions": ["use_hull_biter_charge"],
		"labels": ["player_consumable", "consumable_group_explosive", "damage_type_explosive", "explosive_pass_damage", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(103, 11, 34, 32)
		},
	}
