extends RefCounted

# ==========================================================
# BLUEPRINT ITEMS
# ----------------------------------------------------------
# Data-only item dictionary slice.
# ItemHandler remains the runtime/API owner.
# Current pass adds craft blueprints for player-facing
# primary weapons, secondary weapons, high-need consumables,
# and shields from the separated item DB truth.
# ==========================================================

static func get_items() -> Dictionary:
	return {
		"reinforced_barrier_mk1_blueprint": {
			"id": "reinforced_barrier_mk1_blueprint",
			"item_id": "reinforced_barrier_mk1_blueprint",
			"name": "Reinforced Barrier MK1 Blueprint",
			"display_name": "Reinforced Barrier MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 85, "cobalt": 20, "nickel": 15},
			"craft_result": {"item_id": "reinforced_barrier_mk1", "count": 1},
			"cost": {"iron": 85, "cobalt": 20, "nickel": 15},
			"gain": "reinforced_barrier_mk1",
			"tags": ["blueprint", "craft"],
			"labels": ["recraftable_blueprint"]
		},

		"small_kinetic_rounds_blueprint": {
			"id": "small_kinetic_rounds_blueprint",
			"item_id": "small_kinetic_rounds_blueprint",
			"name": "Small Kinetic Rounds Blueprint",
			"display_name": "Small Kinetic Rounds Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 250},
			"craft_result": {"item_id": "small_kinetic_rounds", "count": 10},
			"cost": {"iron": 250},
			"gain": "small_kinetic_rounds",
			"tags": ["blueprint", "craft"],
			"labels": ["recraftable_blueprint"]
		},

		"navigation_relay_coupler_blueprint": {
			"id": "navigation_relay_coupler_blueprint",
			"item_id": "navigation_relay_coupler_blueprint",
			"name": "Navigation Relay Coupler Blueprint",
			"display_name": "Navigation Relay Coupler Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 800},
			"craft_result": {"item_id": "navigation_relay_coupler", "count": 1},
			"cost": {"iron": 800},
			"gain": "navigation_relay_coupler",
			"tags": ["blueprint", "craft"],
			"labels": ["recraftable_blueprint"]
		},

		"pulse_laser_mk1_blueprint": {
			"id": "pulse_laser_mk1_blueprint",
			"item_id": "pulse_laser_mk1_blueprint",
			"name": "Pulse Laser MK1 Blueprint",
			"display_name": "Pulse Laser MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 90, "cobalt": 25, "nickel": 10},
			"craft_result": {"item_id": "pulse_laser_mk1", "count": 1},
			"cost": {"iron": 90, "cobalt": 25, "nickel": 10},
			"gain": "pulse_laser_mk1",
			"tags": ["blueprint", "craft", "craft_primary"],
			"labels": ["recraftable_blueprint", "blueprint_primary", "tier_1", "blueprint_weapon_primary"]
		},

		"plasma_arc_emitter_blueprint": {
			"id": "plasma_arc_emitter_blueprint",
			"item_id": "plasma_arc_emitter_blueprint",
			"name": "Plasma Arc Emitter Blueprint",
			"display_name": "Plasma Arc Emitter Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 90, "cobalt": 35, "nickel": 10},
			"craft_result": {"item_id": "plasma_arc_emitter", "count": 1},
			"cost": {"iron": 90, "cobalt": 35, "nickel": 10},
			"gain": "plasma_arc_emitter",
			"tags": ["blueprint", "craft", "craft_primary"],
			"labels": ["recraftable_blueprint", "blueprint_primary", "tier_1", "blueprint_weapon_primary"]
		},

		"phase_beam_array_blueprint": {
			"id": "phase_beam_array_blueprint",
			"item_id": "phase_beam_array_blueprint",
			"name": "Phase Beam Array Blueprint",
			"display_name": "Phase Beam Array Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 4.0,
			"craft_cost": {"plasma_arc_emitter": 1, "iron": 180, "cobalt": 55, "nickel": 25},
			"craft_result": {"item_id": "phase_beam_array", "count": 1},
			"cost": {"plasma_arc_emitter": 1, "iron": 180, "cobalt": 55, "nickel": 25},
			"gain": "phase_beam_array",
			"tags": ["blueprint", "craft", "craft_primary"],
			"labels": ["recraftable_blueprint", "blueprint_primary", "tier_2", "blueprint_weapon_primary"]
		},

		"railgun_mk1_blueprint": {
			"id": "railgun_mk1_blueprint",
			"item_id": "railgun_mk1_blueprint",
			"name": "Railgun MK1 Blueprint",
			"display_name": "Railgun MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 120, "nickel": 40},
			"craft_result": {"item_id": "railgun_mk1", "count": 1},
			"cost": {"iron": 120, "nickel": 40},
			"gain": "railgun_mk1",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"railgun_sk1_blueprint": {
			"id": "railgun_sk1_blueprint",
			"item_id": "railgun_sk1_blueprint",
			"name": "Railgun SK1 Blueprint",
			"display_name": "Railgun SK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 115, "cobalt": 10, "nickel": 35},
			"craft_result": {"item_id": "railgun_sk1", "count": 1},
			"cost": {"iron": 115, "cobalt": 10, "nickel": 35},
			"gain": "railgun_sk1",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"mass_driver_blueprint": {
			"id": "mass_driver_blueprint",
			"item_id": "mass_driver_blueprint",
			"name": "Mass Driver Blueprint",
			"display_name": "Mass Driver Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 130, "nickel": 45},
			"craft_result": {"item_id": "mass_driver", "count": 1},
			"cost": {"iron": 130, "nickel": 45},
			"gain": "mass_driver",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"shard_flinger_blueprint": {
			"id": "shard_flinger_blueprint",
			"item_id": "shard_flinger_blueprint",
			"name": "Shard Flinger Blueprint",
			"display_name": "Shard Flinger Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 100, "nickel": 30},
			"craft_result": {"item_id": "shard_flinger", "count": 1},
			"cost": {"iron": 100, "nickel": 30},
			"gain": "shard_flinger",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"micro_torpedo_launcher_blueprint": {
			"id": "micro_torpedo_launcher_blueprint",
			"item_id": "micro_torpedo_launcher_blueprint",
			"name": "Micro Torpedo Launcher Blueprint",
			"display_name": "Micro Torpedo Launcher Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 105, "cobalt": 25, "nickel": 10},
			"craft_result": {"item_id": "micro_torpedo_launcher", "count": 1},
			"cost": {"iron": 105, "cobalt": 25, "nickel": 10},
			"gain": "micro_torpedo_launcher",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"void_charge_cannon_blueprint": {
			"id": "void_charge_cannon_blueprint",
			"item_id": "void_charge_cannon_blueprint",
			"name": "Void Charge Cannon Blueprint",
			"display_name": "Void Charge Cannon Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 4.0,
			"craft_cost": {"micro_torpedo_launcher": 1, "iron": 210, "cobalt": 65, "nickel": 30},
			"craft_result": {"item_id": "void_charge_cannon", "count": 1},
			"cost": {"micro_torpedo_launcher": 1, "iron": 210, "cobalt": 65, "nickel": 30},
			"gain": "void_charge_cannon",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_2", "blueprint_weapon_secondary"]
		},

		"e_basic_energy_pew_pew_blueprint": {
			"id": "e_basic_energy_pew_pew_blueprint",
			"item_id": "e_basic_energy_pew_pew_blueprint",
			"name": "Zapping Pew Pew Blueprint",
			"display_name": "Zapping Pew Pew Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 70, "cobalt": 15},
			"craft_result": {"item_id": "e_basic_energy_pew_pew", "count": 1},
			"cost": {"iron": 70, "cobalt": 15},
			"gain": "e_basic_energy_pew_pew",
			"tags": ["blueprint", "craft", "craft_primary"],
			"labels": ["recraftable_blueprint", "blueprint_primary", "tier_1", "blueprint_weapon_primary"]
		},

		"ion_threader_mk1_blueprint": {
			"id": "ion_threader_mk1_blueprint",
			"item_id": "ion_threader_mk1_blueprint",
			"name": "Ion Threader MK1 Blueprint",
			"display_name": "Ion Threader MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 85, "cobalt": 25, "nickel": 15},
			"craft_result": {"item_id": "ion_threader_mk1", "count": 1},
			"cost": {"iron": 85, "cobalt": 25, "nickel": 15},
			"gain": "ion_threader_mk1",
			"tags": ["blueprint", "craft", "craft_primary"],
			"labels": ["recraftable_blueprint", "blueprint_primary", "tier_1", "blueprint_weapon_primary"]
		},

		"scatter_pulse_mk2_blueprint": {
			"id": "scatter_pulse_mk2_blueprint",
			"item_id": "scatter_pulse_mk2_blueprint",
			"name": "Scatter Pulse MK2 Blueprint",
			"display_name": "Scatter Pulse MK2 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 4.0,
			"craft_cost": {"scatter_pulse_mk1": 1, "iron": 190, "cobalt": 55, "nickel": 35},
			"craft_result": {"item_id": "scatter_pulse_mk2", "count": 1},
			"cost": {"scatter_pulse_mk1": 1, "iron": 190, "cobalt": 55, "nickel": 35},
			"gain": "scatter_pulse_mk2",
			"tags": ["blueprint", "craft", "craft_primary"],
			"labels": ["recraftable_blueprint", "blueprint_primary", "tier_2", "blueprint_weapon_primary"]
		},

		"graviton_needler_mk3_blueprint": {
			"id": "graviton_needler_mk3_blueprint",
			"item_id": "graviton_needler_mk3_blueprint",
			"name": "Graviton Needler MK3 Blueprint",
			"display_name": "Graviton Needler MK3 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 5.0,
			"craft_cost": {"scatter_pulse_mk2": 1, "iron": 320, "cobalt": 95, "nickel": 60},
			"craft_result": {"item_id": "graviton_needler_mk3", "count": 1},
			"cost": {"scatter_pulse_mk2": 1, "iron": 320, "cobalt": 95, "nickel": 60},
			"gain": "graviton_needler_mk3",
			"tags": ["blueprint", "craft", "craft_primary"],
			"labels": ["recraftable_blueprint", "blueprint_primary", "tier_3", "blueprint_weapon_primary"]
		},

		"coil_spitter_mk1_blueprint": {
			"id": "coil_spitter_mk1_blueprint",
			"item_id": "coil_spitter_mk1_blueprint",
			"name": "Coil Spitter MK1 Blueprint",
			"display_name": "Coil Spitter MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 115, "nickel": 40},
			"craft_result": {"item_id": "coil_spitter_mk1", "count": 1},
			"cost": {"iron": 115, "nickel": 40},
			"gain": "coil_spitter_mk1",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"flechette_burst_rack_mk2_blueprint": {
			"id": "flechette_burst_rack_mk2_blueprint",
			"item_id": "flechette_burst_rack_mk2_blueprint",
			"name": "Flechette Burst Rack MK2 Blueprint",
			"display_name": "Flechette Burst Rack MK2 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 4.0,
			"craft_cost": {"flechette_burst_rack_mk1": 1, "iron": 220, "cobalt": 25, "nickel": 70},
			"craft_result": {"item_id": "flechette_burst_rack_mk2", "count": 1},
			"cost": {"flechette_burst_rack_mk1": 1, "iron": 220, "cobalt": 25, "nickel": 70},
			"gain": "flechette_burst_rack_mk2",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_2", "blueprint_weapon_secondary"]
		},

		"spike_driver_mk3_blueprint": {
			"id": "spike_driver_mk3_blueprint",
			"item_id": "spike_driver_mk3_blueprint",
			"name": "Spike Driver MK3 Blueprint",
			"display_name": "Spike Driver MK3 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 5.0,
			"craft_cost": {"flechette_burst_rack_mk2": 1, "iron": 360, "cobalt": 45, "nickel": 110},
			"craft_result": {"item_id": "spike_driver_mk3", "count": 1},
			"cost": {"flechette_burst_rack_mk2": 1, "iron": 360, "cobalt": 45, "nickel": 110},
			"gain": "spike_driver_mk3",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_3", "blueprint_weapon_secondary"]
		},

		"snap_torpedo_rack_mk1_blueprint": {
			"id": "snap_torpedo_rack_mk1_blueprint",
			"item_id": "snap_torpedo_rack_mk1_blueprint",
			"name": "Snap Torpedo Rack MK1 Blueprint",
			"display_name": "Snap Torpedo Rack MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 110, "cobalt": 30, "nickel": 10},
			"craft_result": {"item_id": "snap_torpedo_rack_mk1", "count": 1},
			"cost": {"iron": 110, "cobalt": 30, "nickel": 10},
			"gain": "snap_torpedo_rack_mk1",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"plasma_mine_launcher_mk2_blueprint": {
			"id": "plasma_mine_launcher_mk2_blueprint",
			"item_id": "plasma_mine_launcher_mk2_blueprint",
			"name": "Plasma Mine Launcher MK2 Blueprint",
			"display_name": "Plasma Mine Launcher MK2 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 4.0,
			"craft_cost": {"plasma_mine_launcher_mk1": 1, "iron": 215, "cobalt": 70, "nickel": 35},
			"craft_result": {"item_id": "plasma_mine_launcher_mk2", "count": 1},
			"cost": {"plasma_mine_launcher_mk1": 1, "iron": 215, "cobalt": 70, "nickel": 35},
			"gain": "plasma_mine_launcher_mk2",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_2", "blueprint_weapon_secondary"]
		},

		"cracked_void_mortar_mk3_blueprint": {
			"id": "cracked_void_mortar_mk3_blueprint",
			"item_id": "cracked_void_mortar_mk3_blueprint",
			"name": "Cracked Void Mortar MK3 Blueprint",
			"display_name": "Cracked Void Mortar MK3 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 5.0,
			"craft_cost": {"void_charge_cannon": 1, "iron": 350, "cobalt": 110, "nickel": 60},
			"craft_result": {"item_id": "cracked_void_mortar_mk3", "count": 1},
			"cost": {"void_charge_cannon": 1, "iron": 350, "cobalt": 110, "nickel": 60},
			"gain": "cracked_void_mortar_mk3",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_3", "blueprint_weapon_secondary"]
		},

		"ion_threader_mk1_1_blueprint": {
			"id": "ion_threader_mk1_1_blueprint",
			"item_id": "ion_threader_mk1_1_blueprint",
			"name": "Ion Threader MK1 Blueprint",
			"display_name": "Ion Threader MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 85, "cobalt": 25, "nickel": 15},
			"craft_result": {"item_id": "ion_threader_mk1_1", "count": 1},
			"cost": {"iron": 85, "cobalt": 25, "nickel": 15},
			"gain": "ion_threader_mk1_1",
			"tags": ["blueprint", "craft", "craft_primary"],
			"labels": ["recraftable_blueprint", "blueprint_primary", "tier_1", "blueprint_weapon_primary"]
		},

		"scatter_pulse_mk1_blueprint": {
			"id": "scatter_pulse_mk1_blueprint",
			"item_id": "scatter_pulse_mk1_blueprint",
			"name": "Scatter Pulse MK1 Blueprint",
			"display_name": "Scatter Pulse MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 95, "cobalt": 30, "nickel": 20},
			"craft_result": {"item_id": "scatter_pulse_mk1", "count": 1},
			"cost": {"iron": 95, "cobalt": 30, "nickel": 20},
			"gain": "scatter_pulse_mk1",
			"tags": ["blueprint", "craft", "craft_primary"],
			"labels": ["recraftable_blueprint", "blueprint_primary", "tier_1", "blueprint_weapon_primary"]
		},

		"graviton_needler_mk1_blueprint": {
			"id": "graviton_needler_mk1_blueprint",
			"item_id": "graviton_needler_mk1_blueprint",
			"name": "Graviton Needler MK1 Blueprint",
			"display_name": "Graviton Needler MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 100, "cobalt": 35, "nickel": 20},
			"craft_result": {"item_id": "graviton_needler_mk1", "count": 1},
			"cost": {"iron": 100, "cobalt": 35, "nickel": 20},
			"gain": "graviton_needler_mk1",
			"tags": ["blueprint", "craft", "craft_primary"],
			"labels": ["recraftable_blueprint", "blueprint_primary", "tier_1", "blueprint_weapon_primary"]
		},

		"coil_spitter_mk1_1_blueprint": {
			"id": "coil_spitter_mk1_1_blueprint",
			"item_id": "coil_spitter_mk1_1_blueprint",
			"name": "Coil Spitter MK1 Blueprint",
			"display_name": "Coil Spitter MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 115, "nickel": 40},
			"craft_result": {"item_id": "coil_spitter_mk1_1", "count": 1},
			"cost": {"iron": 115, "nickel": 40},
			"gain": "coil_spitter_mk1_1",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"flechette_burst_rack_mk1_blueprint": {
			"id": "flechette_burst_rack_mk1_blueprint",
			"item_id": "flechette_burst_rack_mk1_blueprint",
			"name": "Flechette Burst Rack MK1 Blueprint",
			"display_name": "Flechette Burst Rack MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 125, "cobalt": 10, "nickel": 45},
			"craft_result": {"item_id": "flechette_burst_rack_mk1", "count": 1},
			"cost": {"iron": 125, "cobalt": 10, "nickel": 45},
			"gain": "flechette_burst_rack_mk1",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"spike_driver_mk1_blueprint": {
			"id": "spike_driver_mk1_blueprint",
			"item_id": "spike_driver_mk1_blueprint",
			"name": "Spike Driver MK1 Blueprint",
			"display_name": "Spike Driver MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 130, "cobalt": 15, "nickel": 50},
			"craft_result": {"item_id": "spike_driver_mk1", "count": 1},
			"cost": {"iron": 130, "cobalt": 15, "nickel": 50},
			"gain": "spike_driver_mk1",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"snap_torpedo_rack_mk1_1_blueprint": {
			"id": "snap_torpedo_rack_mk1_1_blueprint",
			"item_id": "snap_torpedo_rack_mk1_1_blueprint",
			"name": "Snap Torpedo Rack MK1 Blueprint",
			"display_name": "Snap Torpedo Rack MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 110, "cobalt": 30, "nickel": 10},
			"craft_result": {"item_id": "snap_torpedo_rack_mk1_1", "count": 1},
			"cost": {"iron": 110, "cobalt": 30, "nickel": 10},
			"gain": "snap_torpedo_rack_mk1_1",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"plasma_mine_launcher_mk1_blueprint": {
			"id": "plasma_mine_launcher_mk1_blueprint",
			"item_id": "plasma_mine_launcher_mk1_blueprint",
			"name": "Plasma Mine Launcher MK1 Blueprint",
			"display_name": "Plasma Mine Launcher MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 120, "cobalt": 35, "nickel": 15},
			"craft_result": {"item_id": "plasma_mine_launcher_mk1", "count": 1},
			"cost": {"iron": 120, "cobalt": 35, "nickel": 15},
			"gain": "plasma_mine_launcher_mk1",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"cracked_void_mortar_mk1_blueprint": {
			"id": "cracked_void_mortar_mk1_blueprint",
			"item_id": "cracked_void_mortar_mk1_blueprint",
			"name": "Cracked Void Mortar MK1 Blueprint",
			"display_name": "Cracked Void Mortar MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 130, "cobalt": 40, "nickel": 20},
			"craft_result": {"item_id": "cracked_void_mortar_mk1", "count": 1},
			"cost": {"iron": 130, "cobalt": 40, "nickel": 20},
			"gain": "cracked_void_mortar_mk1",
			"tags": ["blueprint", "craft", "craft_secondary"],
			"labels": ["recraftable_blueprint", "blueprint_secondary", "tier_1", "blueprint_weapon_secondary"]
		},

		"repair_kit_blueprint": {
			"id": "repair_kit_blueprint",
			"item_id": "repair_kit_blueprint",
			"name": "Repair Kit Blueprint",
			"display_name": "Repair Kit Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 1000 },
			"craft_result": {"item_id": "repair_kit", "count": 2},
			"cost": {"iron": 1000},
			"gain": "repair_kit",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable"]
		},

		"shield_patch_cell_blueprint": {
			"id": "shield_patch_cell_blueprint",
			"item_id": "shield_patch_cell_blueprint",
			"name": "Shield Patch Cell Blueprint",
			"display_name": "Shield Patch Cell Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"cobalt": 20, "olivine_crystals": 4, "rare_earth_mix": 2},
			"craft_result": {"item_id": "shield_patch_cell", "count": 2},
			"cost": {"cobalt": 20, "olivine_crystals": 4, "rare_earth_mix": 2},
			"gain": "shield_patch_cell",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable"]
		},

		"recharge_kit_blueprint": {
			"id": "recharge_kit_blueprint",
			"item_id": "recharge_kit_blueprint",
			"name": "Recharge Kit Blueprint",
			"display_name": "Recharge Kit Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"cobalt": 18, "water_ice": 8, "helium_3": 4},
			"craft_result": {"item_id": "recharge_kit", "count": 2},
			"cost": {"cobalt": 18, "water_ice": 8, "helium_3": 4},
			"gain": "recharge_kit",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable"]
		},

		"signal_filter_drone_mk1_blueprint": {
			"id": "signal_filter_drone_mk1_blueprint",
			"item_id": "signal_filter_drone_mk1_blueprint",
			"name": "Signal Filter Drone Mk1 Blueprint",
			"display_name": "Signal Filter Drone Mk1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 55, "cobalt": 22, "silicate_dust": 14, "rare_earth_mix": 3},
			"craft_result": {"item_id": "signal_filter_drone_mk1", "count": 1},
			"cost": {"iron": 55, "cobalt": 22, "silicate_dust": 14, "rare_earth_mix": 3},
			"gain": "signal_filter_drone_mk1",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable"]
		},

		"auto_attack_drone_test_mk1_blueprint": {
			"id": "auto_attack_drone_test_mk1_blueprint",
			"item_id": "auto_attack_drone_test_mk1_blueprint",
			"name": "Auto Attack Drone Test Mk1 Blueprint",
			"display_name": "Auto Attack Drone Test Mk1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 55, "cobalt": 22, "silicate_dust": 14, "rare_earth_mix": 3},
			"craft_result": {"item_id": "auto_attack_drone_test_mk1", "count": 1},
			"cost": {"iron": 55, "cobalt": 22, "silicate_dust": 14, "rare_earth_mix": 3},
			"gain": "auto_attack_drone_test_mk1",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable"]
		},

		"auto_moon_pie_blueprint": {
			"id": "auto_moon_pie_blueprint",
			"item_id": "auto_moon_pie_blueprint",
			"name": "Auto Moon Pie Blueprint",
			"display_name": "Auto Moon Pie Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 65, "cobalt": 26, "silicate_dust": 18, "rare_earth_mix": 4},
			"craft_result": {"item_id": "auto_moon_pie", "count": 1},
			"cost": {"iron": 65, "cobalt": 26, "silicate_dust": 18, "rare_earth_mix": 4},
			"gain": "auto_moon_pie",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable", "moonpie_reward"]
		},

		"buster_charge_blueprint": {
			"id": "buster_charge_blueprint",
			"item_id": "buster_charge_blueprint",
			"name": "Buster Charge Blueprint",
			"display_name": "Buster Charge Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 20, "carbon_compounds": 18, "troilite_sulfide": 8},
			"craft_result": {"item_id": "buster_charge", "count": 2},
			"cost": {"iron": 20, "carbon_compounds": 18, "troilite_sulfide": 8},
			"gain": "buster_charge",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable"]
		},

		"breach_charge_blueprint": {
			"id": "breach_charge_blueprint",
			"item_id": "breach_charge_blueprint",
			"name": "Breach Charge Blueprint",
			"display_name": "Breach Charge Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 36, "carbon_compounds": 30, "troilite_sulfide": 14, "magnesium_ore": 8},
			"craft_result": {"item_id": "breach_charge", "count": 2},
			"cost": {"iron": 36, "carbon_compounds": 30, "troilite_sulfide": 14, "magnesium_ore": 8},
			"gain": "breach_charge",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_2", "blueprint_high_need_consumable"]
		},

		"field_repair_spray_mk1_blueprint": {
			"id": "field_repair_spray_mk1_blueprint",
			"item_id": "field_repair_spray_mk1_blueprint",
			"name": "Field Repair Spray MK1 Blueprint",
			"display_name": "Field Repair Spray MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 18, "magnesium_ore": 6, "carbon_compounds": 4},
			"craft_result": {"item_id": "field_repair_spray_mk1", "count": 2},
			"cost": {"iron": 18, "magnesium_ore": 6, "carbon_compounds": 4},
			"gain": "field_repair_spray_mk1",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable"]
		},

		"emergency_capacitor_cell_mk2_blueprint": {
			"id": "emergency_capacitor_cell_mk2_blueprint",
			"item_id": "emergency_capacitor_cell_mk2_blueprint",
			"name": "Emergency Capacitor Cell MK2 Blueprint",
			"display_name": "Emergency Capacitor Cell MK2 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"cobalt": 36, "water_ice": 16, "helium_3": 8, "deuterium_crystals": 4},
			"craft_result": {"item_id": "emergency_capacitor_cell_mk2", "count": 2},
			"cost": {"cobalt": 36, "water_ice": 16, "helium_3": 8, "deuterium_crystals": 4},
			"gain": "emergency_capacitor_cell_mk2",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_2", "blueprint_high_need_consumable"]
		},

		"hull_biter_charge_mk3_blueprint": {
			"id": "hull_biter_charge_mk3_blueprint",
			"item_id": "hull_biter_charge_mk3_blueprint",
			"name": "Hull Biter Charge MK3 Blueprint",
			"display_name": "Hull Biter Charge MK3 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 4.0,
			"craft_cost": {"iron": 55, "carbon_compounds": 46, "troilite_sulfide": 24, "magnesium_ore": 16, "helium_3": 3},
			"craft_result": {"item_id": "hull_biter_charge_mk3", "count": 1},
			"cost": {"iron": 55, "carbon_compounds": 46, "troilite_sulfide": 24, "magnesium_ore": 16, "helium_3": 3},
			"gain": "hull_biter_charge_mk3",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_3", "blueprint_high_need_consumable"]
		},

		"field_repair_spray_mk1_1_blueprint": {
			"id": "field_repair_spray_mk1_1_blueprint",
			"item_id": "field_repair_spray_mk1_1_blueprint",
			"name": "Field Repair Spray MK1 Blueprint",
			"display_name": "Field Repair Spray MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 18, "magnesium_ore": 6, "carbon_compounds": 4},
			"craft_result": {"item_id": "field_repair_spray_mk1_1", "count": 2},
			"cost": {"iron": 18, "magnesium_ore": 6, "carbon_compounds": 4},
			"gain": "field_repair_spray_mk1_1",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable"]
		},

		"emergency_capacitor_cell_mk1_blueprint": {
			"id": "emergency_capacitor_cell_mk1_blueprint",
			"item_id": "emergency_capacitor_cell_mk1_blueprint",
			"name": "Emergency Capacitor Cell MK1 Blueprint",
			"display_name": "Emergency Capacitor Cell MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"cobalt": 18, "water_ice": 8, "helium_3": 4},
			"craft_result": {"item_id": "emergency_capacitor_cell_mk1", "count": 2},
			"cost": {"cobalt": 18, "water_ice": 8, "helium_3": 4},
			"gain": "emergency_capacitor_cell_mk1",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable"]
		},

		"hull_biter_charge_mk1_blueprint": {
			"id": "hull_biter_charge_mk1_blueprint",
			"item_id": "hull_biter_charge_mk1_blueprint",
			"name": "Hull Biter Charge MK1 Blueprint",
			"display_name": "Hull Biter Charge MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 2.0,
			"craft_cost": {"iron": 20, "carbon_compounds": 18, "troilite_sulfide": 8},
			"craft_result": {"item_id": "hull_biter_charge_mk1", "count": 2},
			"cost": {"iron": 20, "carbon_compounds": 18, "troilite_sulfide": 8},
			"gain": "hull_biter_charge_mk1",
			"tags": ["blueprint", "craft", "craft_consumable"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "tier_1", "blueprint_high_need_consumable"]
		},

		"basic_shield_mk1_blueprint": {
			"id": "basic_shield_mk1_blueprint",
			"item_id": "basic_shield_mk1_blueprint",
			"name": "Basic Shield MK1 Blueprint",
			"display_name": "Basic Shield MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 110, "cobalt": 35, "nickel": 20},
			"craft_result": {"item_id": "basic_shield_mk1", "count": 1},
			"cost": {"iron": 110, "cobalt": 35, "nickel": 20},
			"gain": "basic_shield_mk1",
			"tags": ["blueprint", "craft", "craft_shield"],
			"labels": ["recraftable_blueprint", "blueprint_shield", "tier_1"]
		},

		"screen_door_shield_mk1_blueprint": {
			"id": "screen_door_shield_mk1_blueprint",
			"item_id": "screen_door_shield_mk1_blueprint",
			"name": "Screen Door Shield MK1 Blueprint",
			"display_name": "Screen Door Shield MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 100, "cobalt": 25, "nickel": 15},
			"craft_result": {"item_id": "screen_door_shield_mk1", "count": 1},
			"cost": {"iron": 100, "cobalt": 25, "nickel": 15},
			"gain": "screen_door_shield_mk1",
			"tags": ["blueprint", "craft", "craft_shield"],
			"labels": ["recraftable_blueprint", "blueprint_shield", "tier_1"]
		},

		"pulse_guard_mk2_blueprint": {
			"id": "pulse_guard_mk2_blueprint",
			"item_id": "pulse_guard_mk2_blueprint",
			"name": "Pulse Guard MK2 Blueprint",
			"display_name": "Pulse Guard MK2 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 4.0,
			"craft_cost": {"pulse_guard_mk1": 1, "iron": 220, "cobalt": 75, "nickel": 35},
			"craft_result": {"item_id": "pulse_guard_mk2", "count": 1},
			"cost": {"pulse_guard_mk1": 1, "iron": 220, "cobalt": 75, "nickel": 35},
			"gain": "pulse_guard_mk2",
			"tags": ["blueprint", "craft", "craft_shield"],
			"labels": ["recraftable_blueprint", "blueprint_shield", "tier_2"]
		},

		"anchor_barrier_mk3_blueprint": {
			"id": "anchor_barrier_mk3_blueprint",
			"item_id": "anchor_barrier_mk3_blueprint",
			"name": "Anchor Barrier MK3 Blueprint",
			"display_name": "Anchor Barrier MK3 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 5.0,
			"craft_cost": {"pulse_guard_mk2": 1, "iron": 360, "cobalt": 120, "nickel": 65},
			"craft_result": {"item_id": "anchor_barrier_mk3", "count": 1},
			"cost": {"pulse_guard_mk2": 1, "iron": 360, "cobalt": 120, "nickel": 65},
			"gain": "anchor_barrier_mk3",
			"tags": ["blueprint", "craft", "craft_shield"],
			"labels": ["recraftable_blueprint", "blueprint_shield", "tier_3"]
		},

		"screen_door_shield_mk1_1_blueprint": {
			"id": "screen_door_shield_mk1_1_blueprint",
			"item_id": "screen_door_shield_mk1_1_blueprint",
			"name": "Screen Door Shield MK1 Blueprint",
			"display_name": "Screen Door Shield MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 100, "cobalt": 25, "nickel": 15},
			"craft_result": {"item_id": "screen_door_shield_mk1_1", "count": 1},
			"cost": {"iron": 100, "cobalt": 25, "nickel": 15},
			"gain": "screen_door_shield_mk1_1",
			"tags": ["blueprint", "craft", "craft_shield"],
			"labels": ["recraftable_blueprint", "blueprint_shield", "tier_1"]
		},

		"pulse_guard_mk1_blueprint": {
			"id": "pulse_guard_mk1_blueprint",
			"item_id": "pulse_guard_mk1_blueprint",
			"name": "Pulse Guard MK1 Blueprint",
			"display_name": "Pulse Guard MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 115, "cobalt": 40, "nickel": 20},
			"craft_result": {"item_id": "pulse_guard_mk1", "count": 1},
			"cost": {"iron": 115, "cobalt": 40, "nickel": 20},
			"gain": "pulse_guard_mk1",
			"tags": ["blueprint", "craft", "craft_shield"],
			"labels": ["recraftable_blueprint", "blueprint_shield", "tier_1"]
		},

		"anchor_barrier_mk1_blueprint": {
			"id": "anchor_barrier_mk1_blueprint",
			"item_id": "anchor_barrier_mk1_blueprint",
			"name": "Anchor Barrier MK1 Blueprint",
			"display_name": "Anchor Barrier MK1 Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"craft_time": 3.0,
			"craft_cost": {"iron": 130, "cobalt": 45, "nickel": 25},
			"craft_result": {"item_id": "anchor_barrier_mk1", "count": 1},
			"cost": {"iron": 130, "cobalt": 45, "nickel": 25},
			"gain": "anchor_barrier_mk1",
			"tags": ["blueprint", "craft", "craft_shield"],
			"labels": ["recraftable_blueprint", "blueprint_shield", "tier_1"]
		},

		"planetary_resource_rover_blueprint": {
			"id": "planetary_resource_rover_blueprint",
			"item_id": "planetary_resource_rover_blueprint",
			"name": "Planetary Resource Rover Blueprint",
			"display_name": "Planetary Resource Rover Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"orbit_only_blueprint": true,
			"craft_time": 3.0,
			"craft_cost": {"iron": 80, "nickel": 30, "silicate_dust": 20, "carbon_compounds": 18},
			"craft_result": {"item_id": "planetary_resource_rover", "count": 1},
			"cost": {"iron": 80, "nickel": 30, "silicate_dust": 20, "carbon_compounds": 18},
			"gain": "planetary_resource_rover",
			"tags": ["blueprint", "craft", "craft_consumable", "craft_orbit_tool", "planetary_resource_tool"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "blueprint_orbit_tool", "planetary_resource_tool", "tier_1"]
		},

		"planet_recovery_launcher_blueprint": {
			"id": "planet_recovery_launcher_blueprint",
			"item_id": "planet_recovery_launcher_blueprint",
			"name": "Planet Recovery Launcher Blueprint",
			"display_name": "Planet Recovery Launcher Blueprint",
			"type": "blueprint",
			"item_type": "blueprint",
			"subtype": "craft",
			"consumable_group": "craft",
			"stackable": false,
			"max_stack": 1,
			"consumable": false,
			"orbit_only_blueprint": true,
			"craft_time": 3.0,
			"craft_cost": {"iron": 100, "cobalt": 35, "water_ice": 12, "magnesium_ore": 8},
			"craft_result": {"item_id": "planet_recovery_launcher", "count": 1},
			"cost": {"iron": 100, "cobalt": 35, "water_ice": 12, "magnesium_ore": 8},
			"gain": "planet_recovery_launcher",
			"tags": ["blueprint", "craft", "craft_consumable", "craft_orbit_tool", "planetary_resource_tool"],
			"labels": ["recraftable_blueprint", "blueprint_consumable", "blueprint_orbit_tool", "planetary_resource_tool", "tier_1"]
		}
	}
