extends RefCounted

# ==========================================================
# WEAPON ITEMS
# ----------------------------------------------------------
# Data-only item dictionary slice generated from the original
# Control/item_handler.gd item_db source.
# Do not put behavior in this file.
# ==========================================================

static func get_items() -> Dictionary:
	return {
		"smart_guy_focus_lance": {
		"id": "smart_guy_focus_lance",
		"item_id": "smart_guy_focus_lance",
		"name": "Smart Guy Focus Lance",
		"display_name": "Smart Guy Focus Lance",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"damage_type": "energy",
		"damage_value": 34,
		"damage": 34,
		"duration": 3.0,
		"energy_cost": 24,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_smart_guy_focus_lance"],
		"labels": [
		"enemy_weapon",
		"smart_guy_item",
		"primary_weapon_energy",
		"damage_type_energy"
		],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"smart_guy_calculated_rail": {
		"id": "smart_guy_calculated_rail",
		"item_id": "smart_guy_calculated_rail",
		"name": "Smart Guy Calculated Rail",
		"display_name": "Smart Guy Calculated Rail",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"damage_type": "kinetic",
		"damage_value": 22,
		"damage": 22,
		"duration": 4.0,
		"energy_cost": 0,
		"weapon_group": "medium",
		"ammo_group": "medium",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 2,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_smart_guy_calculated_rail"],
		"labels": [
		"enemy_weapon",
		"smart_guy_item",
		"secondary_weapon_kinetic",
		"damage_type_kinetic",
		"ammo_group_medium"
		],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 85, 34, 32)
		},

		"pulse_laser_mk1": {
		"id": "pulse_laser_mk1",
		"item_id": "pulse_laser_mk1",
		"name": "Pulse Laser MK1",
		"display_name": "Pulse Laser MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"damage_type": "energy",
		"damage_value": 50,
		"damage": 50,
		"duration": 3.0,
		"energy_cost": 25,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_pulse_laser"],
		"atlas": "item_sheet_test",
		"texture" : preload("res://images/laser_mk_1_resiz.png")
		},

		"plasma_arc_emitter": {
		"id": "plasma_arc_emitter",
		"item_id": "plasma_arc_emitter",
		"name": "Plasma Arc Emitter",
		"display_name": "Plasma Arc Emitter",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"damage_type": "energy",
		"damage_value": 32,
		"damage": 32,
		"duration": 3.0,
		"energy_cost": 25,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_plasma_arc"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"phase_beam_array": {
		"id": "phase_beam_array",
		"item_id": "phase_beam_array",
		"name": "Phase Beam Array",
		"display_name": "Phase Beam Array",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"damage_type": "energy",
		"damage_value": 45,
		"damage": 45,
		"duration": 3.5,
		"energy_cost": 35,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_phase_beam"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 50, 34, 32)
		},

		"railgun_mk1": {
		"id": "railgun_mk1",
		"item_id": "railgun_mk1",
		"name": "Railgun MK1",
		"display_name": "Railgun MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"damage_type": "kinetic",
		"damage_value": 28,
		"damage": 28,
		"duration": 4.0,
		"energy_cost": 0,
		"weapon_group": "medium",
		"ammo_group": "medium",
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_railgun"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 85, 34, 32)
		},

		"railgun_sk1": {
		"id": "railgun_sk1",
		"item_id": "railgun_sk1",
		"name": "Railgun SK1",
		"display_name": "Railgun SK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"damage_type": "kinetic",
		"damage_value": 12,
		"damage": 12,
		"duration": 1.5,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_per_burst": 1,
		"burst_count": 5,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_railgun"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 85, 34, 32)
		},

		"mass_driver": {
		"id": "mass_driver",
		"item_id": "mass_driver",
		"name": "Mass Driver",
		"display_name": "Mass Driver",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"damage_type": "kinetic",
		"damage_value": 36,
		"damage": 36,
		"duration": 4.5,
		"energy_cost": 0,
		"weapon_group": "medium",
		"ammo_group": "medium",
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_mass_driver"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 85, 34, 32)
		},

		"shard_flinger": {
		"id": "shard_flinger",
		"item_id": "shard_flinger",
		"name": "Shard Flinger",
		"display_name": "Shard Flinger",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"damage_type": "kinetic",
		"damage_value": 22,
		"damage": 22,
		"duration": 3.5,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_per_burst": 1,
		"burst_count": 4,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_shards"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 85, 34, 32)
		},

		"micro_torpedo_launcher": {
		"id": "micro_torpedo_launcher",
		"item_id": "micro_torpedo_launcher",
		"name": "Micro Torpedo Launcher",
		"display_name": "Micro Torpedo Launcher",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"damage_type": "explosive",
		"damage_value": 40,
		"damage": 40,
		"explosive_pass_percent": 0.25,
		"duration": 5.0,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["launch_torpedo"],
		"labels": ["secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 120, 34, 32)
		},

		"void_charge_cannon": {
		"id": "void_charge_cannon",
		"item_id": "void_charge_cannon",
		"name": "Void Charge Cannon",
		"display_name": "Void Charge Cannon",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"damage_type": "explosive",
		"damage_value": 50,
		"damage": 50,
		"explosive_pass_percent": 0.35,
		"duration": 5.5,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_void_charge"],
		"labels": ["secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 120, 34, 32)
		},

		"e_basic_energy_pew_pew": {
		"id": "e_basic_energy_pew_pew",
		"item_id": "e_basic_energy_pew_pew",
		"name": "Zapping Pew Pew",
		"display_name": "Zapping Pew Pew",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"damage_type": "energy",
		"damage_value": 11,
		"damage": 11,
		"duration": 5.0,
		"energy_cost": 25,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_zapping_pew_pew"],
		"atlas": "item_sheet_test",
		"texture" : preload("res://images/laser_mk_1_resiz.png")
		###--------------BLUEPRINTS_______###
		},

		"ion_threader_mk1": {
		"id": "ion_threader_mk1",
		"item_id": "ion_threader_mk1",
		"name": "Ion Threader MK1",
		"display_name": "Ion Threader MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "player_primary_energy",
		"meta_score": 100,
		"meta_pressure": 24,
		"damage_type": "energy",
		"damage_value": 24,
		"damage": 24,
		"duration": 2.4,
		"energy_cost": 30,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_ion_threader"],
		"labels": ["player_weapon", "primary_weapon_energy", "damage_type_energy", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"scatter_pulse_mk2": {
		"id": "scatter_pulse_mk2",
		"item_id": "scatter_pulse_mk2",
		"name": "Scatter Pulse MK2",
		"display_name": "Scatter Pulse MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "player_primary_energy",
		"meta_score": 150,
		"meta_pressure": 34,
		"damage_type": "energy",
		"damage_value": 34,
		"damage": 34,
		"duration": 3.0,
		"energy_cost": 44,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_scatter_pulse"],
		"labels": ["player_weapon", "primary_weapon_energy", "damage_type_energy", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 50, 34, 32)
		},

		"graviton_needler_mk3": {
		"id": "graviton_needler_mk3",
		"item_id": "graviton_needler_mk3",
		"name": "Graviton Needler MK3",
		"display_name": "Graviton Needler MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "player_primary_energy",
		"meta_score": 200,
		"meta_pressure": 46,
		"damage_type": "energy",
		"damage_value": 46,
		"damage": 46,
		"duration": 3.6,
		"energy_cost": 64,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_graviton_needler"],
		"labels": ["player_weapon", "primary_weapon_energy", "damage_type_energy", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"coil_spitter_mk1": {
		"id": "coil_spitter_mk1",
		"item_id": "coil_spitter_mk1",
		"name": "Coil Spitter MK1",
		"display_name": "Coil Spitter MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "player_secondary_kinetic",
		"meta_score": 100,
		"meta_pressure": 56,
		"damage_type": "kinetic",
		"damage_value": 14,
		"damage": 14,
		"duration": 1.8,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 4,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_coil_spitter"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 85, 34, 32)
		},

		"flechette_burst_rack_mk2": {
		"id": "flechette_burst_rack_mk2",
		"item_id": "flechette_burst_rack_mk2",
		"name": "Flechette Burst Rack MK2",
		"display_name": "Flechette Burst Rack MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "player_secondary_kinetic",
		"meta_score": 150,
		"meta_pressure": 88,
		"damage_type": "kinetic",
		"damage_value": 22,
		"damage": 22,
		"duration": 2.6,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 4,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_flechette_burst"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 85, 34, 32)
		},

		"spike_driver_mk3": {
		"id": "spike_driver_mk3",
		"item_id": "spike_driver_mk3",
		"name": "Spike Driver MK3",
		"display_name": "Spike Driver MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "player_secondary_kinetic",
		"meta_score": 200,
		"meta_pressure": 102,
		"damage_type": "kinetic",
		"damage_value": 34,
		"damage": 34,
		"duration": 3.8,
		"energy_cost": 0,
		"weapon_group": "medium",
		"ammo_group": "medium",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_spike_driver"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_medium", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 85, 34, 32)
		},

		"snap_torpedo_rack_mk1": {
		"id": "snap_torpedo_rack_mk1",
		"item_id": "snap_torpedo_rack_mk1",
		"name": "Snap Torpedo Rack MK1",
		"display_name": "Snap Torpedo Rack MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "player_secondary_explosive",
		"meta_score": 100,
		"meta_pressure": 38,
		"damage_type": "explosive",
		"damage_value": 32,
		"damage": 32,
		"explosive_pass_percent": 0.18,
		"duration": 4.2,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["launch_snap_torpedo"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 120, 34, 32)
		},

		"plasma_mine_launcher_mk2": {
		"id": "plasma_mine_launcher_mk2",
		"item_id": "plasma_mine_launcher_mk2",
		"name": "Plasma Mine Launcher MK2",
		"display_name": "Plasma Mine Launcher MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "player_secondary_explosive",
		"meta_score": 150,
		"meta_pressure": 55,
		"damage_type": "explosive",
		"damage_value": 44,
		"damage": 44,
		"explosive_pass_percent": 0.26,
		"duration": 5.0,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["launch_plasma_mine"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 120, 34, 32)
		},

		"cracked_void_mortar_mk3": {
		"id": "cracked_void_mortar_mk3",
		"item_id": "cracked_void_mortar_mk3",
		"name": "Cracked Void Mortar MK3",
		"display_name": "Cracked Void Mortar MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "player_secondary_explosive",
		"meta_score": 200,
		"meta_pressure": 75,
		"damage_type": "explosive",
		"damage_value": 56,
		"damage": 56,
		"explosive_pass_percent": 0.34,
		"duration": 5.8,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_cracked_void_mortar"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 120, 34, 32)
		},

		"vayrax_needler_lance_mk1": {
		"id": "vayrax_needler_lance_mk1",
		"item_id": "vayrax_needler_lance_mk1",
		"name": "Vayrax Needler Lance MK1",
		"display_name": "Vayrax Needler Lance MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "enemy_primary_energy",
		"meta_score": 110,
		"meta_pressure": 18,
		"damage_type": "energy",
		"damage_value": 18,
		"damage": 18,
		"duration": 2.7,
		"energy_cost": 18,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_vayrax_needler_lance"],
		"labels": ["enemy_weapon", "vayrax_item", "primary_weapon_energy", "damage_type_energy", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"raider_arc_stinger_mk2": {
		"id": "raider_arc_stinger_mk2",
		"item_id": "raider_arc_stinger_mk2",
		"name": "Raider Arc Stinger MK2",
		"display_name": "Raider Arc Stinger MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "enemy_primary_energy",
		"meta_score": 165,
		"meta_pressure": 27,
		"damage_type": "energy",
		"damage_value": 27,
		"damage": 27,
		"duration": 3.0,
		"energy_cost": 23,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_raider_arc_stinger"],
		"labels": ["enemy_weapon", "raider_item", "primary_weapon_energy", "damage_type_energy", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 50, 34, 32)
		},

		"guardian_suppression_beam_mk3": {
		"id": "guardian_suppression_beam_mk3",
		"item_id": "guardian_suppression_beam_mk3",
		"name": "Guardian Suppression Beam MK3",
		"display_name": "Guardian Suppression Beam MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "enemy_primary_energy",
		"meta_score": 220,
		"meta_pressure": 36,
		"damage_type": "energy",
		"damage_value": 36,
		"damage": 36,
		"duration": 3.4,
		"energy_cost": 31,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_guardian_suppression_beam"],
		"labels": ["enemy_weapon", "guardian_item", "primary_weapon_energy", "damage_type_energy", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"vayrax_splitter_rail_mk1": {
		"id": "vayrax_splitter_rail_mk1",
		"item_id": "vayrax_splitter_rail_mk1",
		"name": "Vayrax Splitter Rail MK1",
		"display_name": "Vayrax Splitter Rail MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "enemy_secondary_kinetic",
		"meta_score": 110,
		"meta_pressure": 48,
		"damage_type": "kinetic",
		"damage_value": 16,
		"damage": 16,
		"duration": 2.0,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_vayrax_splitter_rail"],
		"labels": ["enemy_weapon", "vayrax_item", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 85, 34, 32)
		},

		"raider_scrap_ripper_mk2": {
		"id": "raider_scrap_ripper_mk2",
		"item_id": "raider_scrap_ripper_mk2",
		"name": "Raider Scrap Ripper MK2",
		"display_name": "Raider Scrap Ripper MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "enemy_secondary_kinetic",
		"meta_score": 165,
		"meta_pressure": 88,
		"damage_type": "kinetic",
		"damage_value": 22,
		"damage": 22,
		"duration": 3.0,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 4,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_raider_scrap_ripper"],
		"labels": ["enemy_weapon", "raider_item", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 85, 34, 32)
		},

		"guardian_punch_driver_mk3": {
		"id": "guardian_punch_driver_mk3",
		"item_id": "guardian_punch_driver_mk3",
		"name": "Guardian Punch Driver MK3",
		"display_name": "Guardian Punch Driver MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "enemy_secondary_kinetic",
		"meta_score": 220,
		"meta_pressure": 102,
		"damage_type": "kinetic",
		"damage_value": 34,
		"damage": 34,
		"duration": 4.1,
		"energy_cost": 0,
		"weapon_group": "medium",
		"ammo_group": "medium",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_guardian_punch_driver"],
		"labels": ["enemy_weapon", "guardian_item", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_medium", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 85, 34, 32)
		},

		"vayrax_puncture_charge_mk1": {
		"id": "vayrax_puncture_charge_mk1",
		"item_id": "vayrax_puncture_charge_mk1",
		"name": "Vayrax Puncture Charge MK1",
		"display_name": "Vayrax Puncture Charge MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "enemy_secondary_explosive",
		"meta_score": 110,
		"meta_pressure": 44,
		"damage_type": "explosive",
		"damage_value": 36,
		"damage": 36,
		"explosive_pass_percent": 0.22,
		"duration": 4.6,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_vayrax_puncture_charge"],
		"labels": ["enemy_weapon", "vayrax_item", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 120, 34, 32)
		},

		"raider_spike_mortar_mk2": {
		"id": "raider_spike_mortar_mk2",
		"item_id": "raider_spike_mortar_mk2",
		"name": "Raider Spike Mortar MK2",
		"display_name": "Raider Spike Mortar MK2",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "enemy_secondary_explosive",
		"meta_score": 165,
		"meta_pressure": 62,
		"damage_type": "explosive",
		"damage_value": 48,
		"damage": 48,
		"explosive_pass_percent": 0.30,
		"duration": 5.4,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_raider_spike_mortar"],
		"labels": ["enemy_weapon", "raider_item", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 120, 34, 32)
		},

		"guardian_echo_torpedo_mk3": {
		"id": "guardian_echo_torpedo_mk3",
		"item_id": "guardian_echo_torpedo_mk3",
		"name": "Guardian Echo Torpedo MK3",
		"display_name": "Guardian Echo Torpedo MK3",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "enemy_secondary_explosive",
		"meta_score": 220,
		"meta_pressure": 82,
		"damage_type": "explosive",
		"damage_value": 60,
		"damage": 60,
		"explosive_pass_percent": 0.36,
		"duration": 6.0,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_guardian_echo_torpedo"],
		"labels": ["enemy_weapon", "guardian_item", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 120, 34, 32)
		},

		"ion_threader_mk1_1": {
		"id": "ion_threader_mk1",
		"item_id": "ion_threader_mk1",
		"name": "Ion Threader MK1",
		"display_name": "Ion Threader MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 1,
		"damage_type": "energy",
		"damage_value": 24,
		"damage": 24,
		"duration": 2.4,
		"energy_cost": 18,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_ion_threader"],
		"labels": ["player_weapon", "primary_weapon_energy", "damage_type_energy", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"scatter_pulse_mk1": {
		"id": "scatter_pulse_mk1",
		"item_id": "scatter_pulse_mk1",
		"name": "Scatter Pulse MK1",
		"display_name": "Scatter Pulse MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 1,
		"damage_type": "energy",
		"damage_value": 30,
		"damage": 30,
		"duration": 3.1,
		"energy_cost": 26,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_scatter_pulse"],
		"labels": ["player_weapon", "primary_weapon_energy", "damage_type_energy", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 50, 34, 32)
		},

		"graviton_needler_mk1": {
		"id": "graviton_needler_mk1",
		"item_id": "graviton_needler_mk1",
		"name": "Graviton Needler MK1",
		"display_name": "Graviton Needler MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 1,
		"damage_type": "energy",
		"damage_value": 38,
		"damage": 38,
		"duration": 3.6,
		"energy_cost": 34,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_graviton_needler"],
		"labels": ["player_weapon", "primary_weapon_energy", "damage_type_energy", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"coil_spitter_mk1_1": {
		"id": "coil_spitter_mk1",
		"item_id": "coil_spitter_mk1",
		"name": "Coil Spitter MK1",
		"display_name": "Coil Spitter MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "kinetic",
		"damage_value": 14,
		"damage": 14,
		"duration": 1.8,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 4,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_coil_spitter"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 85, 34, 32)
		},

		"flechette_burst_rack_mk1": {
		"id": "flechette_burst_rack_mk1",
		"item_id": "flechette_burst_rack_mk1",
		"name": "Flechette Burst Rack MK1",
		"display_name": "Flechette Burst Rack MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "kinetic",
		"damage_value": 20,
		"damage": 20,
		"duration": 2.7,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_flechette_burst"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 85, 34, 32)
		},

		"spike_driver_mk1": {
		"id": "spike_driver_mk1",
		"item_id": "spike_driver_mk1",
		"name": "Spike Driver MK1",
		"display_name": "Spike Driver MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "kinetic",
		"damage_value": 34,
		"damage": 34,
		"duration": 4.2,
		"energy_cost": 0,
		"weapon_group": "medium",
		"ammo_group": "medium",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 2,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_spike_driver"],
		"labels": ["player_weapon", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_medium", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 85, 34, 32)
		},

		"snap_torpedo_rack_mk1_1": {
		"id": "snap_torpedo_rack_mk1",
		"item_id": "snap_torpedo_rack_mk1",
		"name": "Snap Torpedo Rack MK1",
		"display_name": "Snap Torpedo Rack MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "explosive",
		"damage_value": 32,
		"damage": 32,
		"explosive_pass_percent": 0.18,
		"duration": 4.2,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["launch_snap_torpedo"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 120, 34, 32)
		},

		"plasma_mine_launcher_mk1": {
		"id": "plasma_mine_launcher_mk1",
		"item_id": "plasma_mine_launcher_mk1",
		"name": "Plasma Mine Launcher MK1",
		"display_name": "Plasma Mine Launcher MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "explosive",
		"damage_value": 44,
		"damage": 44,
		"explosive_pass_percent": 0.28,
		"duration": 5.0,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["launch_plasma_mine"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 120, 34, 32)
		},

		"cracked_void_mortar_mk1": {
		"id": "cracked_void_mortar_mk1",
		"item_id": "cracked_void_mortar_mk1",
		"name": "Cracked Void Mortar MK1",
		"display_name": "Cracked Void Mortar MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "explosive",
		"damage_value": 58,
		"damage": 58,
		"explosive_pass_percent": 0.38,
		"duration": 6.0,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_cracked_void_mortar"],
		"labels": ["player_weapon", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 120, 34, 32)
		},

		"vayrax_needler_lance_mk1_1": {
		"id": "vayrax_needler_lance_mk1",
		"item_id": "vayrax_needler_lance_mk1",
		"name": "Vayrax Needler Lance MK1",
		"display_name": "Vayrax Needler Lance MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 1,
		"damage_type": "energy",
		"damage_value": 18,
		"damage": 18,
		"duration": 2.7,
		"energy_cost": 18,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_vayrax_needler_lance"],
		"labels": ["enemy_weapon", "vayrax_item", "primary_weapon_energy", "damage_type_energy", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"raider_arc_stinger_mk1": {
		"id": "raider_arc_stinger_mk1",
		"item_id": "raider_arc_stinger_mk1",
		"name": "Raider Arc Stinger MK1",
		"display_name": "Raider Arc Stinger MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 1,
		"damage_type": "energy",
		"damage_value": 26,
		"damage": 26,
		"duration": 3.0,
		"energy_cost": 22,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_raider_arc_stinger"],
		"labels": ["enemy_weapon", "raider_item", "primary_weapon_energy", "damage_type_energy", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 50, 34, 32)
		},

		"guardian_suppression_beam_mk1": {
		"id": "guardian_suppression_beam_mk1",
		"item_id": "guardian_suppression_beam_mk1",
		"name": "Guardian Suppression Beam MK1",
		"display_name": "Guardian Suppression Beam MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "energy",
		"slot": "primary",
		"tier": 1,
		"damage_type": "energy",
		"damage_value": 34,
		"damage": 34,
		"duration": 3.4,
		"energy_cost": 30,
		"weapon_group": "energy",
		"ammo_group": "",
		"ammo_cost": 0,
		"ammo_per_burst": 0,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_guardian_suppression_beam"],
		"labels": ["enemy_weapon", "guardian_item", "primary_weapon_energy", "damage_type_energy", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 50, 34, 32)
		},

		"vayrax_splitter_rail_mk1_1": {
		"id": "vayrax_splitter_rail_mk1",
		"item_id": "vayrax_splitter_rail_mk1",
		"name": "Vayrax Splitter Rail MK1",
		"display_name": "Vayrax Splitter Rail MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "kinetic",
		"damage_value": 16,
		"damage": 16,
		"duration": 2.0,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 3,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_vayrax_splitter_rail"],
		"labels": ["enemy_weapon", "vayrax_item", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 85, 34, 32)
		},

		"raider_scrap_ripper_mk1": {
		"id": "raider_scrap_ripper_mk1",
		"item_id": "raider_scrap_ripper_mk1",
		"name": "Raider Scrap Ripper MK1",
		"display_name": "Raider Scrap Ripper MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "kinetic",
		"damage_value": 22,
		"damage": 22,
		"duration": 3.0,
		"energy_cost": 0,
		"weapon_group": "small",
		"ammo_group": "small",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 4,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_raider_scrap_ripper"],
		"labels": ["enemy_weapon", "raider_item", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_small", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 85, 34, 32)
		},

		"guardian_punch_driver_mk1": {
		"id": "guardian_punch_driver_mk1",
		"item_id": "guardian_punch_driver_mk1",
		"name": "Guardian Punch Driver MK1",
		"display_name": "Guardian Punch Driver MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "kinetic",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "kinetic",
		"damage_value": 32,
		"damage": 32,
		"duration": 4.2,
		"energy_cost": 0,
		"weapon_group": "medium",
		"ammo_group": "medium",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 2,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_guardian_punch_driver"],
		"labels": ["enemy_weapon", "guardian_item", "secondary_weapon_kinetic", "damage_type_kinetic", "ammo_group_medium", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 85, 34, 32)
		},

		"vayrax_puncture_charge_mk1_1": {
		"id": "vayrax_puncture_charge_mk1",
		"item_id": "vayrax_puncture_charge_mk1",
		"name": "Vayrax Puncture Charge MK1",
		"display_name": "Vayrax Puncture Charge MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "explosive",
		"damage_value": 36,
		"damage": 36,
		"explosive_pass_percent": 0.25,
		"duration": 4.6,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_vayrax_puncture_charge"],
		"labels": ["enemy_weapon", "vayrax_item", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(10, 120, 34, 32)
		},

		"raider_spike_mortar_mk1": {
		"id": "raider_spike_mortar_mk1",
		"item_id": "raider_spike_mortar_mk1",
		"name": "Raider Spike Mortar MK1",
		"display_name": "Raider Spike Mortar MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "explosive",
		"damage_value": 48,
		"damage": 48,
		"explosive_pass_percent": 0.32,
		"duration": 5.4,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_raider_spike_mortar"],
		"labels": ["enemy_weapon", "raider_item", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(45, 120, 34, 32)
		},

		"guardian_echo_torpedo_mk1": {
		"id": "guardian_echo_torpedo_mk1",
		"item_id": "guardian_echo_torpedo_mk1",
		"name": "Guardian Echo Torpedo MK1",
		"display_name": "Guardian Echo Torpedo MK1",
		"type": "weapon",
		"item_type": "weapon",
		"subtype": "explosive",
		"slot": "secondary",
		"tier": 1,
		"damage_type": "explosive",
		"damage_value": 56,
		"damage": 56,
		"explosive_pass_percent": 0.38,
		"duration": 6.0,
		"energy_cost": 0,
		"weapon_group": "large",
		"ammo_group": "large",
		"ammo_cost": 1,
		"ammo_per_burst": 1,
		"burst_count": 1,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["fire_guardian_echo_torpedo"],
		"labels": ["enemy_weapon", "guardian_item", "secondary_weapon_explosive_based", "damage_type_explosive", "explosive_pass_damage", "ammo_group_large", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(80, 120, 34, 32)
		}
	}
