extends RefCounted

# ==========================================================
# SHIELD ITEMS
# ----------------------------------------------------------
# Data-only item dictionary slice generated from the original
# Control/item_handler.gd item_db source.
# Do not put behavior in this file.
# ==========================================================

static func get_items() -> Dictionary:
	return {
		"smart_guy_mirror_shield": {
		"id": "smart_guy_mirror_shield",
		"item_id": "smart_guy_mirror_shield",
		"name": "Smart Guy Mirror Shield",
		"display_name": "Smart Guy Mirror Shield",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"shield_hp_max": 75,
		"base_damage_resist": 0.28,
		"base_shield_resist": 0.28,
		"regen_per_second": 3.0,
		"regen_delay": 2.0,
		"swap_time": 1.75,
		"duration": 1.75,
		"steady_energy_drain": 25.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "smart_guy_item", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": [
		"enemy_shield",
		"smart_guy_item",
		"unit_shield_equipped",
		"shield_slider_scaling"
		],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"basic_shield_mk1": {
		"id": "basic_shield_mk1",
		"item_id": "basic_shield_mk1",
		"name": "Basic Shield MK1",
		"display_name": "Basic Shield MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"shield_hp_max": 45,
		"base_damage_resist": 0.2,
		"base_shield_resist": 0.2,
		"regen_per_second": 2.0,
		"regen_delay": 2.0,
		"swap_time": 1.5,
		"duration": 1.5,
		"steady_energy_drain": 20.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["unit_shield_equipped", "shield_slider_scaling"],
		"atlas": "item_sheet_test",
		"region": Rect2(115, 120, 34, 32)
		},

		"reinforced_barrier_mk1": {
		"id": "reinforced_barrier_mk1",
		"item_id": "reinforced_barrier_mk1",
		"name": "Reinforced Barrier MK1",
		"display_name": "Reinforced Barrier MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"shield_hp_max": 90,
		"base_damage_resist": 0.35,
		"base_shield_resist": 0.35,
		"regen_per_second": 4.0,
		"regen_delay": 2.0,
		"swap_time": 2.0,
		"duration": 2.0,
		"steady_energy_drain": 20.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["unit_shield_equipped", "shield_slider_scaling"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"screen_door_shield_mk1": {
		"id": "screen_door_shield_mk1",
		"item_id": "screen_door_shield_mk1",
		"name": "Screen Door Shield MK1",
		"display_name": "Screen Door Shield MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "player_shield",
		"meta_score": 100,
		"meta_capacity": 35,
		"shield_hp_max": 35,
		"base_damage_resist": 0.14,
		"base_shield_resist": 0.14,
		"regen_per_second": 3.0,
		"regen_delay": 1.5,
		"swap_time": 1.1,
		"duration": 1.1,
		"steady_energy_drain": 14.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(115, 120, 34, 32)
		},

		"pulse_guard_mk2": {
		"id": "pulse_guard_mk2",
		"item_id": "pulse_guard_mk2",
		"name": "Pulse Guard MK2",
		"display_name": "Pulse Guard MK2",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "player_shield",
		"meta_score": 150,
		"meta_capacity": 60,
		"shield_hp_max": 60,
		"base_damage_resist": 0.22,
		"base_shield_resist": 0.22,
		"regen_per_second": 2.4,
		"regen_delay": 2.0,
		"swap_time": 1.4,
		"duration": 1.4,
		"steady_energy_drain": 18.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"anchor_barrier_mk3": {
		"id": "anchor_barrier_mk3",
		"item_id": "anchor_barrier_mk3",
		"name": "Anchor Barrier MK3",
		"display_name": "Anchor Barrier MK3",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "player_shield",
		"meta_score": 200,
		"meta_capacity": 90,
		"shield_hp_max": 90,
		"base_damage_resist": 0.30,
		"base_shield_resist": 0.30,
		"regen_per_second": 1.8,
		"regen_delay": 2.4,
		"swap_time": 2.0,
		"duration": 2.0,
		"steady_energy_drain": 24.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"vayrax_flicker_screen_mk1": {
		"id": "vayrax_flicker_screen_mk1",
		"item_id": "vayrax_flicker_screen_mk1",
		"name": "Vayrax Flicker Screen MK1",
		"display_name": "Vayrax Flicker Screen MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"meta_rank": 1,
		"meta_family": "enemy_shield",
		"meta_score": 110,
		"meta_capacity": 45,
		"shield_hp_max": 45,
		"base_damage_resist": 0.18,
		"base_shield_resist": 0.18,
		"regen_per_second": 3.0,
		"regen_delay": 1.6,
		"swap_time": 1.2,
		"duration": 1.2,
		"steady_energy_drain": 16.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["enemy_shield", "vayrax_item", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(115, 120, 34, 32)
		},

		"raider_plate_screen_mk2": {
		"id": "raider_plate_screen_mk2",
		"item_id": "raider_plate_screen_mk2",
		"name": "Raider Plate Screen MK2",
		"display_name": "Raider Plate Screen MK2",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 2,
		"meta_rank": 2,
		"meta_family": "enemy_shield",
		"meta_score": 165,
		"meta_capacity": 70,
		"shield_hp_max": 70,
		"base_damage_resist": 0.25,
		"base_shield_resist": 0.25,
		"regen_per_second": 2.1,
		"regen_delay": 2.0,
		"swap_time": 1.7,
		"duration": 1.7,
		"steady_energy_drain": 20.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["enemy_shield", "raider_item", "unit_shield_equipped", "shield_slider_scaling", "tier_2"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"guardian_lock_barrier_mk3": {
		"id": "guardian_lock_barrier_mk3",
		"item_id": "guardian_lock_barrier_mk3",
		"name": "Guardian Lock Barrier MK3",
		"display_name": "Guardian Lock Barrier MK3",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 3,
		"meta_rank": 3,
		"meta_family": "enemy_shield",
		"meta_score": 220,
		"meta_capacity": 100,
		"shield_hp_max": 100,
		"base_damage_resist": 0.32,
		"base_shield_resist": 0.32,
		"regen_per_second": 1.8,
		"regen_delay": 2.5,
		"swap_time": 2.1,
		"duration": 2.1,
		"steady_energy_drain": 26.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["enemy_shield", "guardian_item", "unit_shield_equipped", "shield_slider_scaling", "tier_3"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"screen_door_shield_mk1_1": {
		"id": "screen_door_shield_mk1",
		"item_id": "screen_door_shield_mk1",
		"name": "Screen Door Shield MK1",
		"display_name": "Screen Door Shield MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"shield_hp_max": 35,
		"base_damage_resist": 0.14,
		"base_shield_resist": 0.14,
		"regen_per_second": 3.0,
		"regen_delay": 1.5,
		"swap_time": 1.1,
		"duration": 1.1,
		"steady_energy_drain": 14.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(115, 120, 34, 32)
		},

		"pulse_guard_mk1": {
		"id": "pulse_guard_mk1",
		"item_id": "pulse_guard_mk1",
		"name": "Pulse Guard MK1",
		"display_name": "Pulse Guard MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"shield_hp_max": 60,
		"base_damage_resist": 0.22,
		"base_shield_resist": 0.22,
		"regen_per_second": 2.4,
		"regen_delay": 2.0,
		"swap_time": 1.4,
		"duration": 1.4,
		"steady_energy_drain": 18.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"anchor_barrier_mk1": {
		"id": "anchor_barrier_mk1",
		"item_id": "anchor_barrier_mk1",
		"name": "Anchor Barrier MK1",
		"display_name": "Anchor Barrier MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"shield_hp_max": 95,
		"base_damage_resist": 0.32,
		"base_shield_resist": 0.32,
		"regen_per_second": 1.8,
		"regen_delay": 2.4,
		"swap_time": 2.0,
		"duration": 2.0,
		"steady_energy_drain": 24.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"labels": ["player_shield", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"vayrax_flicker_screen_mk1_1": {
		"id": "vayrax_flicker_screen_mk1",
		"item_id": "vayrax_flicker_screen_mk1",
		"name": "Vayrax Flicker Screen MK1",
		"display_name": "Vayrax Flicker Screen MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"shield_hp_max": 45,
		"base_damage_resist": 0.18,
		"base_shield_resist": 0.18,
		"regen_per_second": 3.0,
		"regen_delay": 1.6,
		"swap_time": 1.2,
		"duration": 1.2,
		"steady_energy_drain": 16.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["enemy_shield", "vayrax_item", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(115, 120, 34, 32)
		},

		"raider_plate_screen_mk1": {
		"id": "raider_plate_screen_mk1",
		"item_id": "raider_plate_screen_mk1",
		"name": "Raider Plate Screen MK1",
		"display_name": "Raider Plate Screen MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"shield_hp_max": 70,
		"base_damage_resist": 0.25,
		"base_shield_resist": 0.25,
		"regen_per_second": 2.1,
		"regen_delay": 2.0,
		"swap_time": 1.7,
		"duration": 1.7,
		"steady_energy_drain": 20.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["enemy_shield", "raider_item", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		},

		"guardian_lock_barrier_mk1": {
		"id": "guardian_lock_barrier_mk1",
		"item_id": "guardian_lock_barrier_mk1",
		"name": "Guardian Lock Barrier MK1",
		"display_name": "Guardian Lock Barrier MK1",
		"type": "shield",
		"item_type": "shield",
		"subtype": "shield",
		"slot": "shield",
		"tier": 1,
		"shield_hp_max": 100,
		"base_damage_resist": 0.34,
		"base_shield_resist": 0.34,
		"regen_per_second": 1.8,
		"regen_delay": 2.5,
		"swap_time": 2.1,
		"duration": 2.1,
		"steady_energy_drain": 26.0,
		"break_consumes_item": true,
		"repairable_while_active": true,
		"repairable_when_broken": false,
		"stackable": false,
		"max_stack": 1,
		"consumable": false,
		"installed_only": true,
		"grants_actions": ["switch_shield"],
		"tags": ["shield", "energy_drain", "shield_break_consumes", "shield_repairable_while_active"],
		"enemy_logic_tags": ["enemy_can_equip", "enemy_can_replace_broken_shield"],
		"labels": ["enemy_shield", "guardian_item", "unit_shield_equipped", "shield_slider_scaling", "tier_1"],
		"atlas": "item_sheet_test",
		"region": Rect2(150, 120, 34, 32)
		}
	}
